### ISSUE TITLE
No property of name AutomationId found

### ISSUE THREAD

**Issue by RalphAurora** [UXDivers/Gorilla-Player-Support#102]
According to Xamarin's UITest documentation, [https://developer.xamarin.com/samples/xamarin-forms/UsingUITest/](url), the property AutomationId should be used to programmatically detect and access UI elements on a form.  When Gorilla parses Xaml files containing the AutomationId property it raises the error "No Property of name AutomationId found" (XamlParseException).

Is there someway to control the parsing of the Xaml file so that this error can be ignored?  I'm using the Gorilla SDK.

**Comment by LeoHere** [comment]
Hi. Gorilla 0.8.3 is based on an old version of XF where AutomationId was not available. That is why this error occurs. In the new version of Gorilla, that we are about to release, this issue is fixed.

**Comment by LeoHere** [comment]
We release the new version yesterday. Please test it and close the issue if it is fixed.

**Comment by RalphAurora** [comment]
I'm unable to test this since after the upgrade Gorilla no longer finds my translation extension.  Unless there's a way to fix this I'm going to roll back to 0.8.3.

**Comment by LeoHere** [comment]
Are you using the SDK right? 
* Add the GorillaPlayer SDK nuget package to your solution if it is not there yet (you might need to manually remove the old references to 0.8.3 SDK)
* Besides the Gorilla.json you will need to register the assembly that contains your Markup extension in the Config object you create just before the LoadApplication. Please take a look at [this](https://github.com/UXDivers/Gorilla-Player-Support/issues/91).

Let me know if you have any issue.

**Comment by RalphAurora** [comment]
Thanks.  I missed registering the assembly.  Added that in and the extension started working.  Updated forms to 2.2 and AutomationId no longer causes a parsing exception.

Thanks again.  Will close the ticket.
