### ISSUE TITLE
Nuget 0.9.0.4 not compatible with desktop instance

### ISSUE THREAD

**Issue by HEBOS** [UXDivers/Gorilla-Player-Support#104]
Just installed Nuget Gorilla Player 0.9.0.4 SDK, and included it in my App project.
Now the player does not work with current desktop instance (which is 0.8.3.0).
Message is "Performing initial handshake. Almost there!!".

**Comment by LeoHere** [comment]
Hi @HEBOS, yesterday we released the companion gorilla version for those nuget packages. Please install that one to use nuget packages. You should use version 0.9.1.2+
