### ISSUE TITLE
Gorilla Player can't install add-in for version 6.1 of XS

### ISSUE THREAD

**Issue by gaganjitgrewal** [UXDivers/Gorilla-Player-Support#107]
Hi,

With the release of XS 6.x the Gorilla plug in has stopped working and is not getting installed too. I believe that many developers have faced this issue and a compatible gorilla add in is given to them.

Can someone please share the updated gorilla add in with me?

**Comment by jpbrocca** [comment]
Hi @gaganjitgrewal,

we are working on an update that adds support for XS 6.

As soon as it will be ready we will notify our users and you will be able to get it.

Best regards,
JP

**Comment by LeoHere** [comment]
Hi @gaganjitgrewal, did you solve your problems with the addin? If so, can you please close the ticket. Thanks

**Comment by gaganjitgrewal** [comment]
Hi Leo,

Thanks for the updated addin, it has solved my problem.

Best Regards,
Gagan
