### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by NVentimiglia** [UXDivers/Gorilla-Player-Support#108]
- On Windows
- I have installed tools for Xamarin and Visual Studio
- In Xamarin Studio
  - I dont see the connect option when I right click on the xaml file
  - I dont see any connect option in the tools menu
- In Visual Studio
 - I see the gorrila icon in the top right of the xaml code view
 - No idea how to view the file

**Comment by NVentimiglia** [comment]
Update, I found the menu option in tools.

I see the server information when I open up http://localhost:9014/

now what ?

**Comment by jpbrocca** [comment]
Hi @NVentimiglia,

It seems you have everything installed and running on the Gorilla server side of things.
The next steps will be just to deploy the Gorilla Player to each one of your devices.
That way you will be able to preview your XAML pages.

Check the walkthrough on Gorilla player for better understanding:

Right click on Gorilla's icon > Getting Started Walkthrough

You have completed Step 1, now you need to continue with 2 and 3.

Best,
JP

**Comment by NVentimiglia** [comment]
Instructions unclear.

I should run the application as normal ? If that does not work white list the IP and try again ?

**Comment by jpbrocca** [comment]
Hi @NVentimiglia,

sorry, I am not sure I understand what your problem is.

To make Gorilla run you will need to:

1. Install from the installers your downloaded on your VS and/or XS.
2. Once the installation finishes you should have the Gorilla server running. From your comments I understand that you can see the about gorilla page on http://localhost:9014, that means the server is up and running.
3. Now you need to open the Player solution, then deploy it to your devices. It was created after installation and you can get it by clicking on the Gorilla icon on tray and then clicking on the "Show player and samples location" option.
4. After deploying the player on each device you will need to connect. If auto connection does not occur, then you will need to tap on the "Discovered servers" list and connect to the server.
After that, you should be able to open your solution and once you open a XAML file you should be able to preview it on your devices.

If you followed all the previous steps and are you getting any error please let me know.
If you could paste some screen shots that would help too.

Best,
JP

**Comment by NVentimiglia** [comment]
@jpbrocca The player solution, is this a separate solution generated somewhere ?

**Comment by jpbrocca** [comment]
Hi @NVentimiglia,

yes. You can get it by right clicking on the Gorilla icon, then:

![image](https://cloud.githubusercontent.com/assets/15996999/16028989/5ef17e52-31bb-11e6-82f9-9c057da555b2.png)

And then you will find the Player solution:
![image](https://cloud.githubusercontent.com/assets/15996999/16029008/836a8fa8-31bb-11e6-96b2-ba9db1ad2f18.png)

Best,
JP

**Comment by ClaudineiMonteiro** [comment]
I have a Samsung Galaxy S7 phone with the latest version of Android, but when I try to connect in the gorilla playear it appears this error:
![image](https://user-images.githubusercontent.com/16354515/49799847-fc115380-fd13-11e8-8576-92c57edbce7b.png)
Please help me!!!

**Comment by jpbrocca** [comment]
Hi @ClaudineiMonteiro,

From your screen capture, you are not using the latest version.
It seems you have the Gorilla server with the latest, but, you are trying to preview through the deprecated Gorilla Player app from stores.
You need to embed Gorilla SDK in your app to preview properly.

Check the following article on Xamarin's blog for more details:
https://blog.xamarin.com/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/

Best,
JP

**Comment by ClaudineiMonteiro** [comment]
As the app that is in gogleplay is not version 1.5, I opened the project that came with the desktop installer for windows and deployed it to my device. It opens and connects to the server, however when I go on a screenshot of the grial kit and app stops working and closes. What should I do?

De: jpbrocca <notifications@github.com>
Enviada em: terça-feira, 11 de dezembro de 2018 11:35
Para: UXDivers/Gorilla-Player-Support <Gorilla-Player-Support@noreply.github.com>
Cc: ClaudineiMonteiro <claudinei.monteiro@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [UXDivers/Gorilla-Player-Support] How to use it ? (#108)


Hi @ClaudineiMonteiro<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClaudineiMonteiro&data=02%7C01%7C%7Cf036e563f2bc45a3507308d65f868dec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636801428837594001&sdata=Exa8oFFBiLBUL6R3l41hXpQdn1UsX3n77t%2F3%2FrJVCDg%3D&reserved=0>,

From your screen capture, you are not using the latest version.
It seems you have the Gorilla server with the latest, but, you are trying to preview through the deprecated Gorilla Player app from stores.
You need to embed Gorilla SDK in your app to preview properly.

Check the following article on Xamarin's blog for more details:
https://blog.xamarin.com/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblog.xamarin.com%2Fgorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms%2F&data=02%7C01%7C%7Cf036e563f2bc45a3507308d65f868dec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636801428837594001&sdata=4SPOR%2FiiMAY2KBS4i2G9zE37JcYV7wyar92Q6ZpYEHs%3D&reserved=0>

Best,
JP

**Comment by LeoHere** [comment]
@ClaudineiMonteiro If you are previewing Grial UI Kit base application please download the "Gorilla Ready" version from the Grial Admin and run it using the **Gorilla** configuration included in the downloaded solution. See [this](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) section of the documentation for more information.

**Comment by ClaudineiMonteiro** [comment]
that is exactly what I did, but app closed.

De: Leo Rodríguez <notifications@github.com>
Enviada em: segunda-feira, 17 de dezembro de 2018 08:51
Para: UXDivers/Gorilla-Player-Support <Gorilla-Player-Support@noreply.github.com>
Cc: ClaudineiMonteiro <claudinei.monteiro@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [UXDivers/Gorilla-Player-Support] How to use it ? (#108)


@ClaudineiMonteiro<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClaudineiMonteiro&data=02%7C01%7C%7C861d5eb6c4bf41d86ff608d66426b7e2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806514780856065&sdata=YJ4axUkqjOZtDQuwv5QKSkP4pZ8zxuZF3pP65XEiTgo%3D&reserved=0> If you are previewing Grial UI Kit base application please download the "Gorilla Ready" version from the Grial Admin and run it using the Gorilla configuration included in the downloaded solution. See this<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuxdivers.github.io%2FGrial-UI-Kit-Support%2Fdocs.html%23grial-uikit-overview-previewing-grial-with-gorilla-player&data=02%7C01%7C%7C861d5eb6c4bf41d86ff608d66426b7e2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806514780856065&sdata=SXy4i5j2yL6Sf1OWn083SmR8RTw%2FYjTms6I%2FosyHrS0%3D&reserved=0> section of the documentation for more information.

**Comment by LeoHere** [comment]
@ClaudineiMonteiro please attach the exception you see in the Output. Did you see Gorilla Player's initial screen? If possible can you send me a screenshot/video of what you see.

**Comment by ClaudineiMonteiro** [comment]
Yes, I'll do it.

De: Leo Rodríguez <notifications@github.com>
Enviada em: segunda-feira, 17 de dezembro de 2018 09:37
Para: UXDivers/Gorilla-Player-Support <Gorilla-Player-Support@noreply.github.com>
Cc: ClaudineiMonteiro <claudinei.monteiro@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [UXDivers/Gorilla-Player-Support] How to use it ? (#108)


@ClaudineiMonteiro<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClaudineiMonteiro&data=02%7C01%7C%7C4a2eb8250f29411ee27608d6642d2553%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806542387845810&sdata=iWMFUnCBY5YkacR1Yt5OesOa9A7tSXdNjmF1%2F2etnAA%3D&reserved=0> please attach the exception you see in the Output. Did you see Gorilla Player's initial screen? If possible can you send me a screenshot/video of what you see.

**Comment by ClaudineiMonteiro** [comment]
claudinei.monteiro@outlook.com has shared OneDrive files with you. To view them, click the links below.



[icon]

Error GorillaPlayer Samsung Galaxy S7.mp4<https://1drv.ms/v/s!AtX9LsDq7rujk5Q0FMe7zs3kce8JQg>

[icon]

Error GorillaPlayer VS2017.mp4<https://1drv.ms/v/s!AtX9LsDq7rujk5QzaYPHkZIAPO7V5w>



Attach the videos, the gorillaplayer is running on the phone normally, when I enter the visual studio 2017 and open the XAML happens the error shown in the video of the cell phone, what do I do?
