### ISSUE TITLE
Gorilla not working on latest Mac Xamarin Studio 6.0

### ISSUE THREAD

**Issue by willjstevens** [UXDivers/Gorilla-Player-Support#112]
On my Mac I just did an upgrade to Xamarin 6.0 but now, no Gorilla options are exposed in the Tools menu or the right-click context menu. Examples include not seeing the menu item under Tools, for Gorilla and Connect to Gorilla; or the context menu item on a XAML file to Stick to Gorilla. I think something in the upgrade clobbered Gorilla. 

Environment info:
 - Xamarin Studio Community 6.0 (build 5174)
 - Mac OS X El Capitan, 10.11.5
 - Gorilla 0.9.1.2

**Comment by yberstad** [comment]
Hi!

This is maybe not helping you much, but I have all the same versions as you are referring to, and it is working for me. I did however not upgrade the Xamarin Studio from a previous version, but as a "fresh install"...

**Comment by LeoHere** [comment]
Try reinstalling the addin.
1) close XS
2) click the tray icon and select install extras
3) only leave checked XS addin

Hope it helps.

**Comment by willjstevens** [comment]
Thanks LeoHere, your solution worked. For some reason I thought I already had those both done when re-installing the new version. Looks like I needed to do it again. 

Thanks to both of you.
