### ISSUE TITLE
Cannot find UXDivers.Artina.Player DLLs anywhere

### ISSUE THREAD

**Issue by willjstevens** [UXDivers/Gorilla-Player-Support#115]
This link says you should find them in the Gorilla samples directory after installing them:
[https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK)

But there is no /lib directory found anywhere. They should be there after installing from Gorilla. I am on Gorilla 0.9.1.2.

**Comment by LeoHere** [comment]
Hi @willjstevens, 
Sorry for that. The Gorilla SDK document was outdated. Now those libs are delivered as nuget packages for simplicity. 

I have just updated the Gorilla SDK document. So please, read it again.

**Comment by willjstevens** [comment]
Thanks! That worked nicely.

**Comment by willjstevens** [comment]
Just noticed something from the updated doc - there is a missing DLL reference for UXDivers.Gorilla.Player.Droid.Player. 

https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK 

 Did something get refactored but no Nuget package?

**Comment by willjstevens** [comment]
Looks like it was a typo on the documentation code sample. 

It said `UXDivers.Gorilla.**Player**.Droid.Player` but really should just be `UXDivers.Gorilla.iOS.Player`.

**Comment by LeoHere** [comment]
Fixed! Thanks a lot!
