### ISSUE TITLE
Player times out while connecting to server after update

### ISSUE THREAD

**Issue by srkrathore** [UXDivers/Gorilla-Player-Support#116]
I recently downloaded the latest version of gorilla player and updated it with the older one. After that when I am executing the Player code to install the player on my emulator it's not able to connect to sever and keeps on giving message that it's trying to connect to server.

**Comment by LeoHere** [comment]
Can you provide me more details about your environment:
- Windows or Mac?
- Which emulator are you using?
- XS or VS?

Are you using auto discovery or manual ?

Are you using the Gorilla Player SDK or just the standard player?

What version is displayed below the Gorilla logo in the Player App?

**Comment by srkrathore** [comment]
Hey Leo, Thanks for looking into this,

Here are the details you asked for

Windows or Mac?     Mac OS X El Capitan
Which emulator are you using?  iPhone 6s iOS 9.3 
XS or VS?    XS 6
Are you using auto discovery or manual ? 
Auto Discovery.

Are you using the Gorilla Player SDK or just the standard player? 
I guess it's just standard player as I was following the documents where it says to build the player solution to deploy player on emulator.

What version is displayed below the Gorilla logo in the Player App?
0.9.1.2

**Comment by LeoHere** [comment]
Ok, thanks for the info. 

So, the player discover the server but it hangs while connecting, right? Or does the server does not discover any server at all?

Did you tried to connect manually? same results?

**Comment by srkrathore** [comment]
Yes the player discovers the server but times-out in effort to connect to it. It didn't gives me time to manually connect to it as it automatically starts connecting when the player starts.  I can send you the log file if you provide me ur email as Github doesn't allows to upload log files.

**Comment by LeoHere** [comment]
l r o d r i g u e z A T u x d i v e r s . c o m

**Comment by srkrathore** [comment]
mailed you the files it will be from srkrathore at  gmail . com

**Comment by LeoHere** [comment]
Thanks. I just write you back. Let's continue from there until we find the solution.

**Comment by LeoHere** [comment]
@srkrathore if this issue is solved, can you please close the ticket? Thanks

**Comment by srkrathore** [comment]
Thanks Leo for reminding and your help

**Comment by joshd-infotrack** [comment]
What was the solution for this?  I am now experiencing a similar issue....

**Comment by LeoHere** [comment]
@joshd-infotrack, is it the first time you use Gorilla? Or you have been using it for a while and suddenly you start getting experiencing this issue? Can you provide me more details about you environment?

**Comment by joshd-infotrack** [comment]
Been using it for a while and it had been working great.  Now I am getting the following error messages:
"There was an issue registering the solution with the gorilla (The underlying connection was closed: The connection was closed unexpectedly)."  OR
"Error occured while setting Gorilla Target XAML.  File _mypage.xaml_ (The underlying connection was closed: The connection was closed unexpectedly)."

Looking into the logs, there are a number of exceptions, mostly in the VisualStudio.log, such as:
Error: 51 : Exception 'The underlying connection was closed: The connection was closed unexpectedly.' ocurred while doing 'SetTarget(...)
Error: 58 : Exception 'Unable to connect to the remote server' ocurred while doing 'SetTarget(...)
Error: 48 : Exception 'The underlying connection was closed: The connection was closed unexpectedly.' ocurred while doing 'AddSolution(...)
Error: 21 : Exception 'The underlying connection was closed: An unexpected error occurred on a receive.' ocurred while doing 'SetTarget(...)
*Errors alternate between SetTarget/AddSolution

And in the gorillaHost.log I can see ""Error occurred while reading the registry key \\Software\\Wow6432Node\\Xamarin\\XamarinStudio, message: process exited with code 1"

Yet everything seems to connect - I can start host server on PC, open localhost:9014 in browser, I can connect to this from the emulator and also access through the device browser and Visual Studio also connects and the Connectivity Test passes every time.

These errors seem to pop up about a minute or so after everything is connected and I should be able to start previewing.  I'm also not seeing the little Gorilla icon in the top right of my XAML code in VS to indicate which page I am previewing.

For the record I'm running Windows 10 (64), VS 15 Update 3, Gorilla Player 0.9.1.2.  If you see anything glaringly obvious feel free to provide a suggestion **BUT** with that being said, it may be an environment issue so I will confirm that first before you start chasing ghosts.  

Let me know what course of action I should take if I still have issues as it may be a little while before I can afford too much time trying to resolve this (even though it IS super useful).  This is probably not the forum for this but a final question if I may - have you had any experience with AV interfering with Gorilla?

Thanks for the prompt response :)
