### ISSUE TITLE
No Grid in a Grid Displayed on Android

### ISSUE THREAD

**Issue by svwu** [UXDivers/Gorilla-Player-Support#117]
Hi There!
I got the problem, that a Grid in a Grid won't be shown on Android devices.

This is my example Code:
`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App4.Views.Elements">`
 `<Grid>`
    `<Grid.RowDefinitions>`      
      ` <RowDefinition Height="20" />`
      `<RowDefinition Height="20" />`
      `<RowDefinition Height="20" />`
      `<RowDefinition Height="20" />`
    ` <RowDefinition Height="20" />`
     ` <RowDefinition Height="20" />`
      `<RowDefinition Height="20" />`
   ` </Grid.RowDefinitions>`
  `<Grid.ColumnDefinitions>`
   ` <ColumnDefinition Width="*" />`
 ` </Grid.ColumnDefinitions>  `
   ` <Label Grid.Column="0" Grid.Row="1" Text="ElementPreview" />`  `      
    <Grid Grid.Column="0" Grid.Row="2" Orientation="Vertical">`      
      `<Grid.RowDefinitions>`
        `<RowDefinition Height="30" />`
        `<RowDefinition Height="30" />`
        `<RowDefinition Height="30" />`
       ` <RowDefinition Height="30" />`
       ` <RowDefinition Height="30" />`
      `</Grid.RowDefinitions>`
      `<Grid.ColumnDefinitions>`
        `<ColumnDefinition Width="200"/>`
      `</Grid.ColumnDefinitions>`
      
      <Label Grid.Row="0" Grid.Column="0" Text="Entry" />
      <Entry Grid.Row="1" Grid.Column="0" Text="TEXT" />
      <Label Grid.Row="0" Grid.Column="1" Text="Eigenschaften" />
      <Label Grid.Row="2" Text="Keyboards" />
`    </Grid>   `
`  </Grid>`
`</ContentPage>'`

I get everything shown on my iPad, but I won't get the second line on my inner Grid displayed on Android.
These lines are not shown:

      <Entry Grid.Row="1" Grid.Column="0" Text="TEXT" />
      <Label Grid.Row="0" Grid.Column="1" Text="Eigenschaften" />
      <Label Grid.Row="2" Text="Keyboards" />

Is this normal Android Behaviour, or a bug?

Best Regards,
Sven

**Comment by jpbrocca** [comment]
Hi @svwu,

can you paste the whole code again?...I am not sure if you made a mistake on your XAML or if it is when you wanted to format the post here.

If you want just send me the file to jpbrocca@uxdivers.com.

Best,
JP

**Comment by svwu** [comment]
The big space is just a big space and I don't know where it comes from... bad format here :/ But there is no code missing

**Comment by jpbrocca** [comment]
I just pasted your Grid code on a page of a project I am working and this is what I get (the entrys look different but this is because of my project):

![image](https://cloud.githubusercontent.com/assets/15996999/16153890/b9a609ce-347e-11e6-8b38-c743c5004239.png)

**Comment by jpbrocca** [comment]
I think your code has some issues by the way ;)

**Comment by svwu** [comment]
It was a matter of sizes...
I'm sorry ;)

**Comment by jpbrocca** [comment]
Just replace the "*" with "Auto".

I am going to close this issue now.

Thanks!
JP
