### ISSUE TITLE
How can I do a clean install? I am getting errors trying to install v0.9.1.2

### ISSUE THREAD

**Issue by Korayem** [UXDivers/Gorilla-Player-Support#118]
I did uninstall previous v0.8 version before doing anything yet I am getting an Error `Oh snap! Gorilla Player Addin for Xamarin Studio installation failed :(`

I have Xamarin Studio 6 build 5174 installed

**Comment by LeoHere** [comment]
Hi! Are you in a mac or windows? Currently we only provide the XS addin for XS on Mac. If you need the windows addin I will generate it for you. Let me know.

**Comment by Korayem** [comment]
Windows :)

**Comment by Korayem** [comment]
Previous version was working fine on Windows

**Comment by LeoHere** [comment]
Hi, attached is the addin for XS6 on Windows. 

You will need to manually install it:
* Within Xamarin Studio: Go to Xamarin Studio > Add-ins > Install from file... and the Select the download mpack
* From Command line: Enter the following command (path might differ)

    `"/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" setup install -y 
"UXDivers.Artina.Player.Addins.Gorilla Player_0.9.1.2.mpack"`

Here is the mpack, I needed to zip it to upload it. You will need to unzip it before installing.

[UXDivers.Artina.Player.Addins.Gorilla Player_0.9.1.2.mpack.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/321694/UXDivers.Artina.Player.Addins.Gorilla.Player_0.9.1.2.mpack.zip)

**Comment by jpbrocca** [comment]
Hi @Korayem, hope you are doing fie :)
Did you succeed installing on Windows ?

Best,
JP

**Comment by Korayem** [comment]
@jpbrocca hey! how's it going :)

I was on a trip and didn't have time to test this before.

I confirm it's working like a charm now on Windows :+1: 

But you guys should fix this at exe setup file level like it used to work before without any workarounds like one described here

**Comment by jpbrocca** [comment]
Hi @Korayem, how was your trip? Hope you enjoyed it!
Yes, this is just a hot fix to avoid creating an additional version just for this...don't worry it will be OK on next version.

thanks for your confirmation and for all your help!
Best,
JP

**Comment by YhorbyMatias** [comment]
Thanks thats work for me on windows 10 XS 6.0
