### ISSUE TITLE
"Could not load file or assembly 'UXDivers.Artina.Shared' or one of its dependencies."

### ISSUE THREAD

**Issue by willjstevens** [UXDivers/Gorilla-Player-Support#120]
I receive this error when trying to get Gorilla to stick to my Grial XAML files.  

"**Could not load file or assembly 'UXDivers.Artina.Shared' or one of its dependencies.**"

I am using Gorilla 0.9.1.2, with the player deployed to my iPhone 6 device.  I followed all the instructions here: [Gorilla-SDK](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) 

I bought Grial Kit (extended license) and am trying to get its custom renderers and XAML to show in the Gorilla player. 

This is the code in **AppDelegate.cs**:

`LoadApplication(UXDivers.Gorilla.iOS.Player.CreateApplication(
				new UXDivers.Gorilla.Config("Good Gorilla")
					.RegisterAssemblyFromType<UXDivers.Artina.Shared.CircleImage>()
					.RegisterAssemblyFromType<UXDivers.Artina.Grial.BrandBlock>()
				));
` 
And this in **Gorilla.json**:

`	"knownAssemblies": [
		{
			"name": "UXDivers.Artina.Shared",
			"types": null
		}
        ,
		{
			"name": "UXDivers.Artina.Grial",
			"types": null
		}
	]`

I then deployed the player SDK code to my device as described in the link. But when going to do a "Stick Gorilla to this" right-click option, it gives me the error on the device.
I thought I had everything setup correctly, with all the assemblies declared and deployed correctly in the two spots (AppDelegate.cs and Gorilla.json)

Please help!

**Comment by LeoHere** [comment]
That is weird, everything seems to be in place. 

When you said you deploy the Player, you mean you run Grial.iOS or the one that contains AppDelegate.cs mentioned above, right? (I ask, just to double check)

You can try two things:
* Clean and rebuild, then deploy.
* Clean and rebuild + remove manually the app from the device and then deploy

**Comment by willjstevens** [comment]
That did it!  A full clean, rebuild, deploy is what it took.  Huh.

**Comment by attrib75** [comment]
I'm having the same issue.  Clean, rebuild successfully, no difference

**Comment by willjstevens** [comment]
Did you put the register assembly code into our AppDelegate.cs? And comparable into MainActivity? Then do the clean/rebuild/etc.

**Comment by attrib75** [comment]
yes

**Comment by attrib75** [comment]
Sorry I put this under the wrong project, this is for Grial Kit

**Comment by thE-iNviNciblE** [comment]
i've the same Error Visual Studio 2017 prof can't find any UXDriver Artina references... what is the problem, can't uninstall it. i had done a setup for the grial kit nuget repository...
