### ISSUE TITLE
Difference in WYSISYG

### ISSUE THREAD

**Issue by msmrajesh** [UXDivers/Gorilla-Player-Support#125]
![fromdevice](https://cloud.githubusercontent.com/assets/18613834/16254661/e4c452c0-385f-11e6-918e-030498f126be.png)
![fromgorilla](https://cloud.githubusercontent.com/assets/18613834/16254662/e4cc7874-385f-11e6-9fa4-880e59dd2cb5.png)

Hi,
I downloaded Gorilla 0.9.1.2 on another desktop in another location and it has no issue in connecting to the Gorilla server from the device. However I am getting a black background for all the screens in spite of changing the theme.

To change the theme i used this in MainActivity.cs

[Activity(Theme = "@android:style/Theme.Holo.Light", Label = "Expense Manager", Icon = "@drawable/icon", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]

When running on the device I am getting the desired output. You can see the difference in the two attachments. Why does this happen. Is there any work around to get the same look and feel in Gorilla as well as the device.

As a workaround I used this on every page

  <ContentPage.BackgroundColor>
    <OnPlatform x:TypeArguments="Color" iOS="#fff0f0f0" Android="White" />
  </ContentPage.BackgroundColor>

Thanks,
Rajesh

**Comment by LeoHere** [comment]
Hi!, In order to preview stuff that you control through code, like the theme you mentioned or rendering a custom renderer, you will need to use the SDK. See [this](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) for an explanation on how to integrate it to your app. 

Hope it helps.

**Comment by jpbrocca** [comment]
Hi @msmrajesh, hope you are doing fine.
If you follow @LeoHere's indications you will be able to preview your theme.
I am closing this bug now, but if you can reopen it if you need it.
Thanks!
JP
