### ISSUE TITLE
XamarinStudio add-in is broken with 6.0.1 update

### ISSUE THREAD

**Issue by asmodeus74** [UXDivers/Gorilla-Player-Support#126]
After updating XS to 6.0.1 Gorilla add-in stopped working
Error message is: Required MonoDevelop.Core v6, found v6.0.1

**Comment by LeoHere** [comment]
Please download the compatible addin from here https://goo.gl/rjYktl

**Comment by asmodeus74** [comment]
Working perfectly.. Thanks
