### ISSUE TITLE
Gorilla SDK documentation clarification on NuGet package installs

### ISSUE THREAD

**Issue by WillemMali** [UXDivers/Gorilla-Player-Support#128]
Hi,

I'd like to know more about where to install the Gorilla SDK NuGet's; the documentation currently says this:

Add a reference to Gorilla Player SDK nuget packages.

I think it'd be nice if it specified if you have to add it to your iOS/Android projects, and whether to install it to referenced PCL's as well, for example:

For my projects I have the following structure:

```
My.Apps (shared by all apps)
My.Apps.Droid (shared by all Android apps)

My.SpecificApp (a specific app, uses: My.Apps)
My.SpecificApp.Droid (Android specific stuff for specifc app, uses: My.SpecificApp, My.Apps.Droid)
```

Which of these projects would need to have the SDK NuGet installed for it to work?

**Comment by LeoHere** [comment]
Hi. Thanks for your comments.

Ok, I updated the SDK document to clarify this a little bit more. 

Within  "Why the SDK ?" when it says "For the former approach you need to:" I clarify it a little more with this:
* Add [Gorilla Player SDK nuget](https://www.nuget.org/packages/UXDivers.GorillaPlayer.SDK/) packages to  Xamarin.iOS and Xamarin.Android projects. Packages should be added only to those projects that act as an entry point to your application (i.e. where the `LoadApplication` is performed). 

And within "How to preview Grial custom renderers on Gorilla Player" I clarify it a little more with this:
* Add [Gorilla Player SDK nuget](https://www.nuget.org/packages/UXDivers.GorillaPlayer.SDK/) packages to platform specific projects that act as an entry point to your application (i.e. Grial.iOS and Grial.Droid).

Let me know if you think it is clear enough or we should clarify any particular point?

In your case, from what you said I think you should add those packages only in the My.SpecificApp.Droid.  I'm assuming that My.Apps.Droid is a library and you never try to execute an app from it alone, right?

**Comment by WillemMali** [comment]
Hi Leo,

That sounds great. I don't think it needs more clarification than you've given.

Yes, My.Apps.Droid is a library and only used for stuff like Android-specific renderer implementations.

I'm still not able to get the SDK to work, because it's unable to find the right assemblies, but that's another problem and I already opened an issue for it.

**Comment by jpbrocca** [comment]
Hi @WillemMali and @LeoHere, I am closing this issue since it seems to be fixed now.
You can re open it if needed.
Thanks!
