### ISSUE TITLE
Xamarin Studio Update crashes Gorilla.

### ISSUE THREAD

**Issue by harleygomes** [UXDivers/Gorilla-Player-Support#129]
Hi !

Today I installed the last Xamarin Studio's update and after that my Gorilla Player is not showing previews anymore.

The Gorilla suffix (Gorilla) isn't appearing beside of my pages on the solution explorer.

Do you know something about that ?

**Comment by jpbrocca** [comment]
Hi @harleygomes,

Did you take a look at this?
https://github.com/UXDivers/Gorilla-Player-Support/issues/118

Are you on windows or Mac?
Just in case the above fails, could you provide more info about your OS, Xamarin Studio version, etc ?

Thanks!
JP

**Comment by harleygomes** [comment]
Hey @jpbrocca !

I'm using a Mac. The Gorilla Player server is installed and running.

My Xamarin and iOS infos here:

Xamarin Studio Business
Version 6.0.1 (build 8)

Runtime:
	Mono 4.4.1 (mono-4.4.0-branch-c7sr0/4747417) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 404010000

Xamarin.Profiler
Not Installed

Apple Developer Tools
Xcode 7.3.1 (10188.1)
Build 7D1014

Xamarin.Mac
Version: 2.8.1.4 (Xamarin Business)

Xamarin.Android
Version: 6.1.1.1 (Xamarin Business)
Android SDK: /Users/harleyaraujo/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)

SDK Tools Version: 24.4.1
SDK Platform Tools Version: 23.0.1
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Android Player
Version: 0.6.5
Location: /Applications/Xamarin Android Player.app

Xamarin.iOS
Version: 9.8.1.4 (Xamarin Business)
Hash: 3cf8aae
Branch: c7sr0
Build date: 2016-06-20 16:09:58-0400

Build Information
Release ID: 600010008
Git revision: 0ecc3639cde21616d675e4fdef1b858d166dd065
Build date: 2016-06-20 13:16:51-04
Xamarin addins: a9252e6df4851fbbed1f9c6228e7b6dd1b475ac5
Build lane: monodevelop-lion-cycle7-sr0

Operating System
Mac OS X 10.11.5
Darwin Harleys-MacBook-Air.local 15.5.0 Darwin Kernel Version 15.5.0
    Tue Apr 19 18:36:36 PDT 2016
    root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

Enabled user installed addins
Gorilla Player 0.9.1.2

thanks!

**Comment by mattdavid** [comment]
I have a similar issue (gorilla not working in xamarin studio on mac).

When I look at the Add-in Manager, I see this error for it:
"This add-in can't be loaded due to missing dependencies"
"The following dependencies required by this add-in are not available:
Required: MonoDevelop.Core v6.0, found v6.0.1
Required: MonoDevelop.Ide v6.0, found v6.0.1"

**Comment by LeoHere** [comment]
Please download the compatible addin from https://goo.gl/rjYktl

**Comment by jpbrocca** [comment]
You are fast @LeoHere! 
I was going to paste that here! :)

@harleygomes, @mattdavid guys if this works for you please leave a comment so we can close this issue.

Thanks a lo and happy previewing! :)
JP

**Comment by harleygomes** [comment]
@LeoHere and @jpbrocca already downloaded and installed the add-in and now is loaded into Xamarin Studio, but I'm not previewing yet. :(

The server is running ( on version 0.9.1.2) and Connected with my emulator, but the XAML files not containing the suffix (Gorilla)

**Comment by jpbrocca** [comment]
Glad to hear that @harleygomes! :)
Enjoy!
