### ISSUE TITLE
GorillaPlayer 0.9.1.2 incompatible with Xamarin Studio 6.0.1

### ISSUE THREAD

**Issue by fadookie** [UXDivers/Gorilla-Player-Support#130]
<img width="313" alt="screen shot 2016-06-24 at 11 24 05 am" src="https://cloud.githubusercontent.com/assets/110764/16346825/37c8a9ea-39fe-11e6-89d5-77e64d62363d.png">

**Comment by LeoHere** [comment]
Please download the compatible addin from https://goo.gl/rjYktl

**Comment by fadookie** [comment]
Thanks, that worked!
