### ISSUE TITLE
Grollia Player AddIn for Xamarin Studio on Windows

### ISSUE THREAD

**Issue by afzalali15** [UXDivers/Gorilla-Player-Support#133]
Hello Team UXDivers, 

Kudos, Gorilla Player works perfectly on my Mac machine with Xamarin Studio.

But when I try to install addins on my windows machine, all other addins get installed(Visual Studio and Player) but addin for Xamarin Studio gives ohh snap.

Here is the log for the same::

{"level":"info","message":"Starting Gorilla App...","timestamp":"2016-07-07T14:03:35.513Z"}
{"level":"info","message":"[Analytics] Setting user afzal.ali@servpro.in (generated=false)","timestamp":"2016-07-07T14:03:38.357Z"}
{"level":"info","message":"Gorilla Server: info: Starting Gorilla (0.9.1.2)...\r\n","timestamp":"2016-07-07T14:03:42.341Z"}
{"level":"info","message":"Gorilla Server: info: Starting server with (serverName: Gorilla on Jarvis, port: 9014, discoveryPort: 14578)\r\n","timestamp":"2016-07-07T14:03:44.575Z"}
{"level":"info","message":"Gorilla Server: info: Preloading assembly mscorlib, Version=2.0.5.0.\r\n","timestamp":"2016-07-07T14:03:47.028Z"}
{"level":"info","message":"Gorilla Server: info: Listening at http://0.0.0.0:9014\r\n","timestamp":"2016-07-07T14:03:47.028Z"}
{"level":"info","message":"Gorilla Server reported it reached ready state","timestamp":"2016-07-07T14:03:47.075Z"}
{"level":"info","message":"Gorilla Server: GORILLA:READY","timestamp":"2016-07-07T14:03:47.075Z"}
{"level":"info","message":"Gorilla Server: info: Discovery Server listening on 0.0.0.0:14578\r\n","timestamp":"2016-07-07T14:03:47.107Z"}
{"level":"info","message":"MDTool: Xamarin Studio Add-in Setup Utility\r\n","timestamp":"2016-07-07T14:05:07.453Z"}
{"level":"info","message":"MDTool: ERROR: ","timestamp":"2016-07-07T14:05:07.748Z"}
{"level":"info","message":"MDTool: The package '::MonoDevelop.Core v5.10.3' could not be found in any repository\r\n","timestamp":"2016-07-07T14:05:07.749Z"}
{"level":"info","message":"MDTool: ERROR: ","timestamp":"2016-07-07T14:05:07.750Z"}
{"level":"info","message":"MDTool: The package '::MonoDevelop.Ide v5.10.3' could not be found in any repository\r\n","timestamp":"2016-07-07T14:05:07.752Z"}
{"level":"info","message":"MDTool: Not all dependencies could be resolved.\r\n","timestamp":"2016-07-07T14:05:07.753Z"}
{"level":"error","message":"MDTool exitcode 4294967295","timestamp":"2016-07-07T14:05:07.913Z"}
{"level":"info","message":"Skipping Copying extra files","timestamp":"2016-07-07T14:05:07.914Z"}

**Comment by LeoHere** [comment]
Hi. Please see [this post](https://github.com/UXDivers/Gorilla-Player-Support/issues/118). In short, 0.9.1.2 installer has support for XS6.0 only for Mac. You will find a link to the addin you need in that post.

**Comment by afzalali15** [comment]
Thanx LeoHere, installing add-in manually worked for me..
