### ISSUE TITLE
Blank white page

### ISSUE THREAD

**Issue by danialbakhsheshi** [UXDivers/Gorilla-Player-Support#135]
I already bind the emulator but it shows a blank white page , the Icon appeared on XAML file but nothing in player

**Comment by LeoHere** [comment]
Can you please post the XAML your are previewing?

**Comment by LeoHere** [comment]
@danialbakhsheshi closing the issue. If you experience the problem again please open a new issue and include the XAML and a short description of the environment where you are executing.
