### ISSUE TITLE
SampleData.json for a grouped ListView

### ISSUE THREAD

**Issue by johankson** [UXDivers/Gorilla-Player-Support#137]
I have the following XAML

* Bound to Items
* Grouped by Category

```xaml 
<ListView HasUnevenRows="true" 
				IsGroupingEnabled="true" GroupDisplayBinding="{Binding Category}"
				ItemsSource="{Binding Items}" CachingStrategy="RecycleElement">
<ListView.ItemTemplate>
	<DataTemplate>
        <ViewCell>
          <ContentView>
             <StackLayout Orientation="Horizontal" Padding="17,4">
					<Image Source="{Binding Image}" />
            		<Label Text="{Binding Text}" FontAttributes="Bold" />
       		</StackLayout>
          </ContentView>
        </ViewCell>
      </DataTemplate>
    </ListView.ItemTemplate>
  </ListView>
```

How would you define the sampledata in SampleData.json for this?

My guess would have been something like this. It generates the categories correct but with one row for each property, ignoring the Items collection.

```json
{
	"ThePage.xaml" : {
		"Items" : 
		[
			{  "Category":"Ducks",
				"Items": [
					{ "Text": "Yellow Duck", "Image": "duck.png" }
				]
			}, 
			{  "Category":"Horses",
				"Items": [
					{ "Text": "Black Horse", "Image": "horse.png" }
				]
			},
		]
	}
}

```

**Comment by LeoHere** [comment]
Hi! Currently you can't generate sample data for a grouped ListView using JSON. 

The workaround in order to be able to preview XAML with sample data would be: 
1. setup [Gorilla SDK](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) in your solution
2. define the sample data using plain C# and register the assembly containing those clases with Gorilla.
3. bind the sample data to your XAML using ```x:Static```

**Comment by johankson** [comment]
That kinda takes away the simplicity of modeling sample data. Is there any way to extend the parsing or the player? I'm happy to help if there is anything I can do.

**Comment by LeoHere** [comment]
Hi @johankson. I have just added a document explaining how to do this [here](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Sample-Data-&-ListView.IsGroupingEnabled). If you were able to preview your grouped ```ListView``` please close the issue.

**Comment by johankson** [comment]
Hi!

Sorry for the delayed response. I get this error (see image) when I try to
add the * to the sample data.

Any hints?

Best regards

// Johan

​

2016-08-08 0:52 GMT+02:00 Leonardo Rodríguez <notifications@github.com>:

**Comment by johankson** [comment]
Sorry about the last error. It was a typo in my sample data. It works as
expected. Closing the issue.

2016-08-22 11:31 GMT+02:00 Johan Karlsson <johan.kson@gmail.com>:
