### ISSUE TITLE
Xlabs don't working

### ISSUE THREAD

**Issue by mfranc28** [UXDivers/Gorilla-Player-Support#138]
Don't make preview of Xlabs components like ExtendendLabel and ExtendedEntry

**Comment by LeoHere** [comment]
Actually there is a sample installed with 0.9.1.2 showing how to preview a XLabs controls. Click in the Gorilla tray icon, then select "Show Player and Samples Location" and go to sample "Sample/HowTo/XLabsControlsSample".

Basically you will need to [setup the SDK](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) and register the XLabs assemblies.

**Comment by LeoHere** [comment]
I'm closing the issue for now. Please feel free to reopen it if the issue persists.
