### ISSUE TITLE
Could not initiate Gorilla, port 9014 in use on Mac

### ISSUE THREAD

**Issue by EdHubbell** [UXDivers/Gorilla-Player-Support#140]
I used to be able to start Gorilla without a problem, but something seems to have changed. 

1) The player no longer connects to the server. I'm on player version 0.9.1.2. I used to hit 'auto discover' and things would work fine. Now the player never sees the server. Macbook pro server side, Nexus 5x player side.

2) Stopping and restarting Gorilla means I get the error above - Seems like Gorilla server side isn't closing out the open port when it is closed. I'm not even sure where to change Gorilla server's port. I looked for a .json config file but I didn't find it. Might have looked in the wrong place, tho.

3) With Auto Discover not working, I could try Manual Setup, but I'm not sure what to specify for parameters. The phone is connected via USB C cable and USB Debugging is enabled.

Any help is appreciated.

**Comment by LeoHere** [comment]
The fact that you get that error when you restart Gorilla suggests there is a instance of Gorilla that does not shutdown correctly. 

Please do as follows:
* quit Gorilla
* open activity monitor and find out any process with the name "Gorilla", "Gorilla Player" or "Gorilla Player Helper" and force them to stop.
* start gorilla player again

After that you should not get the port error. 

If that fixes the problem please close the issue. Otherwise let me know!

**Comment by EdHubbell** [comment]
Thanks, @LeoHere - That takes care of #2. 

I still can't get the Player to see the server. The player says 
'Looking for server named "Gorilla on Eds-Macbook-Pro', please wait...'
The 'Connect' button remains disabled. 

It used to auto connect just fine. Although I may have been using the version from the Play Store. 

When I go to http://localhost:9014/, I can see that the server name is indeed Gorilla on Eds-MacBook-Pro. 

I'm no longer in an urgent state - I'm running the player in the iOS simulator on my box while simultaneously editing my solution in Xamarin Studio. That's working for me great (wish I had known I could do that earlier).

**Comment by LeoHere** [comment]
Hey, is the device connected to the same WIFI as the desktop machine? For the auto-discovery to work you need them to be.

**Comment by EdHubbell** [comment]
It was not. I honestly had no idea that's how they were connecting. I thought it was because I was plugged in via USB. 

Thanks! 
~Ed
