### ISSUE TITLE
Feature Suggestion: iOS player should not standby

### ISSUE THREAD

**Issue by rossdempster** [UXDivers/Gorilla-Player-Support#146]
An idea for the suggestion box. I am constantly having to re-wake my phone while designing my forms because the phone goes into standby (which, incidentally, breaks the connection and I have to reconnect the player).

I am so keen on this feature I even went and looked up the solution on StackOverflow for you. I believe something like the following should do the trick:
[UIApplication sharedApplication].idleTimerDisabled = YES;

I reckon this is a good thing to do by default, but perhaps an option would be good if there is some disagreement about that.

Workaround is to manually switch standby off for the whole phone, which I inevitably forget to switch back on when I'm finished designing!

**Comment by LeoHere** [comment]
Cool, thanks!

BTW, in the meantime, you should be able to do it yourself, just add this to the player project and deploy it to your devices.

**Comment by mrdfortefour** [comment]
Hi Leo, thanks for the tip! I've added the code to prevent standby but when I run the custom build it does not seem to detect my screen correctly. It runs as a smaller iPhone4-style application in the middle of my larger iPhone6 screen. Unfortunately, not much use for my purpose!

Had a dig around in the Xamarin settings for the Gorilla project to see if there was something different but nothing obvious stands out.

**Comment by LeoHere** [comment]
Hi @rossdempster, that is weird. Are you still having this issue? Can you send an screenshot of what you are seeing?

BTW, we added your suggestion to Gorilla. You will have a setting to control this which by default will be preventing the device from sleeping. 

It will be included in next version. Thanks!

**Comment by rossdempster** [comment]
Hi Leo that's great news - thanks! I'll get a screenshot for you as soon as I can. I'm not going to be able to do this for a few days though sorry.

**Comment by LeoHere** [comment]
@rossdempster I found these two links that might be related to the app being incorrectly scaled in the iphone 6, take a look.

http://conceptdev.blogspot.com.uy/2014/09/iphone-6-and-6-plus-launch-images-for.html

https://forums.xamarin.com/discussion/30071/xamarin-forms-1-3-1-page-rendering-odd-for-ios-devices-larger-than-a-4s

**Comment by rossdempster** [comment]
@LeoHere Thanks for the info. That was the issue! Will you be updating the base project your end? I guess there might some other people with this problem. Looking forward to the updated version.
