### ISSUE TITLE
Xamarin Studio can't connect with Gorilla

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Gorilla-Player-Support#151]
Xamarin Studio has started not being able to connect to Gorilla Player. It was working fine, but now I'm getting a message:

"Failed to connect. Error getting response stream (ReadDone2): ReceiveFailure"

This is with Xamarin Studio 6.0.2 and Gorilla Player 0.91.2.

As mentioned above - this was working fine.

**Comment by LeoHere** [comment]
did you try restarting gorilla?

**Comment by james-lavery** [comment]
@LeoHere Hi Leo - yes I did, but it didn't work. However, a machine restart (and/or something else!) has now fixed the problem!
