### ISSUE TITLE
OSX Gorilla Player and Sample app not working

### ISSUE THREAD

**Issue by kitkat14** [UXDivers/Gorilla-Player-Support#152]
Hi Guys,

I wanted to try your tool to get rid of the 1000 times you have to build to see what you are doing but I when i tried running the app on the simulator (9.3) i am getting this:
https://i.imgsafe.org/d87b0a1117.png

Android has also 100 errors...

FYI:
Using xamarin studio (on alpha channel) on Macbook OSX 10.11.4

**Comment by LeoHere** [comment]
The image only shows Android errors. Are you having error is iOS too? Which ones? 

Probably packages where not correctly restored and/or you might need to install/update Andorid SDK.

You can also download the player directly from the Apple Store/Google Play. But that is possible only on a real device.

**Comment by kitkat14** [comment]
Yeah probably  that was the problem. What i did to solve it:

Build -> Clean All.
Build -> Rebuild All.

Issue solved and got it working 👍
