### ISSUE TITLE
Cannot connect to Gorilla from physical Android device

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Gorilla-Player-Support#153]
I'm using the Gorilla SDK in my app, and it's working fine on iOS and Android emulators.

It also works fine on an iPhone.

I'm having problems on an Android device - A  Samsung GT-19505.

It's not discovering Gorilla Player using Auto Discover, and using Manual Setup to enter 10.0.0.14:9014 (which is what my iPhone is connecting to), results in the message:

_Could not connect to the server (is it down?). Retrying..._

Do I need to change an Android setting to allow it to see Gorilla Player?

I'm using Xamarin Studio 6.0.2 with Gorilla Player 0.9.1.2

**Comment by LeoHere** [comment]
Hi James,

Couple of things to check:
* Do you have the INTERNET permission set in your Android app?
* Is the real devices connected to the same wifi as your desktop?
* If you download Gorilla from Google Play, can you connect to the server?

**Comment by james-lavery** [comment]
The device wasn't on the same wireless - all working now thanks.
