### ISSUE TITLE
Not able to install plugin in Xamarin Studio

### ISSUE THREAD

**Issue by Subha-murali** [UXDivers/Gorilla-Player-Support#155]
When I try to install addin for Xamarin Studio, following error is shown:

_Oh snap! Gorilla Player Addin for Xamarin Studio installation failed :(_

How to fix it?

Using Following Xamarin Version

Xamarin Studio
Version 5.10.2 (build 56)
Runtime:
	Microsoft .NET 4.0.30319.34014
	GTK+ 2.24.23 (MS-Windows theme)
	GTK# 2.12.30

Xamarin.Profiler
Not Installed

Does this plugin works with free Visual Studio Community Edition or not?

Please reply as soon as possible.

**Comment by jpbrocca** [comment]
Hi @Subha-murali,

did you make sure you had Xamarin Studio closed before installing ?

Yes, Gorilla Player works with Visual Studio.

Regard,
JP

**Comment by Subha-murali** [comment]
@jpbrocca ,

Yes Xamarin Studio was closed only. As soon as I click Install Now button, its immediately throwing error.

**Comment by jpbrocca** [comment]
@Subha-murali,

Did you also make sure you didn't have a previous version of Gorilla running while installing?

**Comment by Subha-murali** [comment]
I have installed only one Gorilla Player

**Comment by Subha-murali** [comment]
No reply???

**Comment by LeoHere** [comment]
Probably you will need to upgrade XS at least to 5.10.3 or jump to XS 6.

In order to confirm that is the problem please install the addin manually within Xamarin Studio and let me know the error you get. Go to Tools->Addin Manager->Install from file... and choose the .mpack located "c:\Program Files (x86)\Gorilla Player\resources\Addins"

**Comment by Subha-murali** [comment]
![gorillaplayererror](https://cloud.githubusercontent.com/assets/14836267/18044511/e1526138-6deb-11e6-8df4-c673a3d13c7e.png)

Please find attached file

**Comment by LeoHere** [comment]
Ok, thanks! Yes, you will need to upgrade to 5.10.3 at least in order to install the addin or use visual studio community.

If you upgrade to XS 6, you will need to manually download/install the addin from [here](https://github.com/UXDivers/Gorilla-Player-Support/issues/118) (it is attached in the issue).

**Comment by Subha-murali** [comment]
Thanks for the immediate response, my current Xamarin Studio version is 5.10.2. So I need to upgrade it to 5.10.3, any other updates required apart from Studio?

**Comment by LeoHere** [comment]
I don't think so...

**Comment by Subha-murali** [comment]
Still no success, I upgraded to Xamarin Studio 6.0.2 and downloaded UXDivers.Artina.Player.Addins.Gorilla.Player_0.9.1.2.mpack zip from above link. When I try to run that command, I am getting following error:

_'UXDivers.Artina.Player.Addins.Gorilla' is not recognized as an internal or exte
rnal command,
operable program or batch file._

**Comment by Subha-murali** [comment]
Thank you, I successfully installed it, but getting following error while trying to connect.
![connecterror](https://cloud.githubusercontent.com/assets/14836267/18053117/8f9f3782-6e1b-11e6-8aa2-aa854a80844d.png)

**Comment by Subha-murali** [comment]
Still I am not able to see preview in Gorilla Player, I have installed Gorilla in my physical device, it is running, but both auto and manual server not working. I tried by connecting IP address.

![aboutgorilla](https://cloud.githubusercontent.com/assets/14836267/18078794/0a03749a-6eab-11e6-8fff-9076c9cbf166.png)


Please help me to resolve my current issue also. I don't have any listening ip address in my about. How to do manual setup?

**Comment by jpbrocca** [comment]
Did you check this page?
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Troubleshoouting-Connectivity

**Comment by Subha-murali** [comment]
I tested in real device its working fine, but in order to test in emulator, is there any way to install Gorilla Player in Emulator without using playstore?

**Comment by LeoHere** [comment]
Yes, you can deploy it yourself. 

Right click the Gorilla Icon in the tray and choose "Show Player and Samples Location". Open the player solution and deploy it to your emulator.

**Comment by Subha-murali** [comment]
Getting following error while deploying player.sln

_Deployment failed. Assembly synchronization error._

**Comment by LeoHere** [comment]
Did you tried clean/rebuild? I think you should restart XS before doing so. Usually, when you get this type of errors from Xamarin Studio the only way out is to reset everything. You even might need to remove packages and rerestore them...

**Comment by Subha-murali** [comment]
Okay, now error and all I fixed it, but Gorilla player in my emulator not connecting with server. Same IP address working in real device.

**Comment by Subha-murali** [comment]
Thanks for your support, it is working...

**Comment by jpbrocca** [comment]
Great, I am closing this bug then.
