### ISSUE TITLE
Default constructor not found for type UXDivers.Gorilla.Platform.XamlLoader

### ISSUE THREAD

**Issue by micuentadecasa** [UXDivers/Gorilla-Player-Support#157]
Hi, I'm using Xamaring Studio community, when I try to debug gorilla player in IOS I can't debug because I don't have XCode 7.3 , but I change in the solution properties the linker options to Link all and it starts to debug, but when it plays it it throw an exception:

Default constructor not found for type UXDivers.Gorilla.Platform.XamlLoader

in the line LoadApplication (Player.CreateApplication(new Config("Gorilla on xxx-MacBook-Pro.local")));

**Comment by LeoHere** [comment]
Link all setting usually is not able to infer all the usages and needs to be further instructed in order to not remove required stuff. Why are you trying to do this? Did you know you can download the Player directly from the Apple Store?

**Comment by micuentadecasa** [comment]
I don't want to upgrady my Osx so I need to use that config. Anyway I saw recently that like you said I can download the app from the apple store and from play store, my problema now is other that I will post in a new issue. You can close this issue and thanks.
