### ISSUE TITLE
Unknown issue related to ISSUE_XAML_AREA

### ISSUE THREAD

**Issue by perry89** [UXDivers/Gorilla-Player-Support#161]
Hello

While trying to load one of my pages I get a following Error:

Cannot read property "ISSUE_XAML_AREA" of undefined.

Problem is related to ListView binding. Using RelativeSource property.

**Comment by LeoHere** [comment]
Can you send me the logs located at ```/Users/<Your User>/.gorilla/logs``` (more info [here](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-Player-logs-location))? 
to l r o d r i g u e z at u x d i v e r s . c o m

**Comment by perry89** [comment]
e-mail send, thank you :)

**Comment by perry89** [comment]
Hi Leo

Never mind, restarting PC fixed the issue.

Regards


Wojciech Boczarski
Junior Software Engineer
[cid:image001.jpg@01D1AC6B.193A62F0]<http://www.microsec.co.uk/>

Tel:      +44 (0)23 9251 8254 (DDI)
Email:  wojciech.boczarski@microsec.co.uk
Web:   www.microsec.co.uk
[cid:image005.png@01D13356.2FDB99E0]<https://www.linkedin.com/company/microsec-ltd->

Microsec Ltd is a limited company registered in England and Wales. Registered number: 1462783. Registered office: Langstone Technology Park, Langstone Road, Havant, PO9 1SA

[cid:image001.png@01D03AD4.46684260]<https://xamarin.com/>  [cid:image009.jpg@01D03B07.4F924420] <http://www.tickitplus.org/certification/certified-organisations.aspx>   [cid:image011.jpg@01D03B07.4F924420] <http://www.tickitplus.org/certification/certified-organisations.aspx>   [cid:image004.png@01D04F6E.BA3B4DF0] <http://www.tickitplus.org/certification/certified-organisations.aspx>

**Comment by jalvarezz** [comment]
Hi, im having this issue trying to use a RelativeLayout with Contraints but with a different message:

Message: "Cannot read property of 'ISSUE_XAML_AREA' of undefined"

Log File: "Gorilla Server: warn: Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 2.2.0.45"

Dont know why the Gorilla server is picking the core 2.0 instead of the 2.2.

**Comment by LeoHere** [comment]
@jalvarezz Can you share the XAML you are trying to preview or the part causing the issue ?
