### ISSUE TITLE
(Converter) Cant't resolve resources : Converter

### ISSUE THREAD

**Issue by Mr-Pearce** [UXDivers/Gorilla-Player-Support#162]
Hi i have a problem using Converters.

i have A Button Like This
`<Button Text="Connect" IsVisible="{Binding Connected, Converter={StaticResource InverseBooleanConverter}}"/>
    `
and the Converter is defined inside my app.xaml like this
Namespace:
`xmlns:converter="clr-namespace:MyProject.Views.Converter;assembly=MyProject"`

```
<Application.Resources>
    <ResourceDictionary>
             <converter:InverseBooleanConverter x:Key="InverseBooleanConverter" />
    </ResourceDictionary>
  </Application.Resources>
```

Converter is written like this

```
namespace MyProject.Views.Converter
{
    public class InverseBooleanConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter,
          System.Globalization.CultureInfo culture)
        {
            if (targetType != typeof(bool))
                throw new InvalidOperationException("The target must be a boolean");

            return !(bool)value;
        }

        public object ConvertBack(object value, Type targetType, object parameter,
          System.Globalization.CultureInfo culture)
        {
            throw new NotSupportedException();
        }
    }
}
```
But when i want to open my view with this button Gorilla Player has the Error "Resources not found "Can't resolve resources: InverseBooleanConverter"

**Comment by LeoHere** [comment]
Are you using Gorilla SDK? If not, you will need to use it, so Gorilla knows about your converters. [This](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) document will explain how to do it.

**Comment by Mr-Pearce** [comment]
The linked Document is not that helpful on this point.
Also there is no sample about the Gorilla.json file. 

I now tried following with the SDK.

- Added the SDK to my Droid and Ios  Projects

- MainActivity

```
LoadApplication(UXDivers.Gorilla.Droid.Player.CreateApplication(ApplicationContext,
  new UXDivers.Gorilla.Config("Good Gorilla")
  .RegisterAssemblyFromType<Views.Converter.InverseBooleanConverter>()));
```

- AppDelegate

```
LoadApplication(UXDivers.Gorilla.iOS.Player.CreateApplication(
  new UXDivers.Gorilla.Config("Good Gorilla")
  .RegisterAssemblyFromType<Views.Converter.InverseBooleanConverter>()));
```

- Gorilla.json (dont really know how to use it for this)

```
{
  "knownAssemblies": [
    {
      "name": "OrkaMobile.Views.Converter",
      "types": [ "InverseBooleanConverter" ]
    }
  ]
}
```

**Comment by LeoHere** [comment]
You got most of it right. There only seems to be an issue in the ```Gorilla.json``` file.

If your converter XML namespace is declared as follows:

~~~
xmlns:converter="clr-namespace:MyProject.Views.Converter;assembly=MyProject"
~~~

your ```Gorilla.json``` should include the assembly ```MyProject``` as follows:

~~~
{
  "knownAssemblies": [ 
  	{ "name": "MyProject" }
  ]
}
~~~

In the section titled "How to preview Grial custom renderers on Gorilla Player" of the document item 3 there is a link to download a ```Gorilla.json``` sample. 

Please let me know if it solves your issue.

**Comment by Mr-Pearce** [comment]
Now it works.
Looks like i have not seen that Gorilla.json in the document is a link.

**Comment by LeoHere** [comment]
Great!
