### ISSUE TITLE
Fontawesome icons

### ISSUE THREAD

**Issue by ShiroYacha** [UXDivers/Gorilla-Player-Support#169]
Hi, I had an issue previewing fontawesome icons from Grial in gorilla player. It only shows a placeholder box with a cross in the middle. When I run the app it works fine. I am using the 2nd method to integrate gorilla player by extending the Player solution and inject dependencies on my .netstandard shared Xamarin forms project, setting the Config object and the Gorilla.json. I have also put the fontawesome-webfont in the Player project. The other features of Grial works correctly.

Also I would like to point out that the documentation concerning extending the Player solution is pretty thin. I didn't want to inject Gorilla SDK directly because switching the build configuration all the time is pretty awkward.

Thanks!

**Comment by LeoHere** [comment]
Please follow the steps described [here](https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/How-to-add-icons-to-your-project) in order to install fontawesome in your extended-player solution. Let me know if you have any issue.

Regarding the documentation, got it. We will improve it ASAP.

**Comment by ShiroYacha** [comment]
Hi, I found out that I missed the Assembly flag for the font renderer in the player project. It works now, Thanks!
