### ISSUE TITLE
Missing namespace definition for vm

### ISSUE THREAD

**Issue by heluvatuff** [UXDivers/Gorilla-Player-Support#173]
Just installed Gorilla Player on my emulator and I can preview the XAML in the sample apps. My Xamarin Forms app will not preview. I'm getting the following error "Missing namespace definition for vm". Even when I add a brand new content page I cannot preview it.

**Comment by LeoHere** [comment]
Probably Gorilla is complaining about something in the ```App.xaml```. Can you share your ```App.xaml``` content?

**Comment by heluvatuff** [comment]
That was my problem. I'm using mvvmlight and the following was missing from the <Application> Element of my App.xaml

xmlns:vm="clr-namespace:AppPortalMobile.ViewModels">

Thank you
