### ISSUE TITLE
JSON integer 

### ISSUE THREAD

**Issue by nbandla9** [UXDivers/Gorilla-Player-Support#174]
1476795200015 is too longer or small for an int32,  path serverStartTime line 1 position 1465[](url)

Using Visual studio 2015 update 3 
Gorilla 9.1.2

No errors in actual application

![error](https://cloud.githubusercontent.com/assets/22913382/19479558/439405c0-953f-11e6-9860-43c1b5492cd8.png)

Thanks
Nag

**Comment by LeoHere** [comment]
Hi, this error was something we fixed long time ago. It is weird you are getting it now. 

When are you getting this error? each time you try to preview? Have you ever been able to preview a page in the past? 
Are you using the Gorila SDK or you just deployed the player to the emulator?

**Comment by nbandla9** [comment]
this is the first time using it. 

yes just deployed player via VS15 into emulator and edited XAML project in my VS, did not get any preview except this error. 

i installed 8.0X version previously as it not connecting to server i reinstalled with newer version, now its connected but getting above error. 
Thanks

**Comment by LeoHere** [comment]
When you said you Installed 8.0X you mean Gorilla Player 0.8.3? If the player you are using is 0.8.3 it makes sense to get this error. Please, make sure you are using the 0.9.1.2 player in the device. 

My recommendation would be:
1. uninstall the player from the emulator
2. open the player solution
3. make sure 0.9.1.2 nuget packages are being referenced from the player
4. perform a clean & rebuild
5. deploy the player to the emulator again

Please let me know the result.

**Comment by nbandla** [comment]
hi

yes above has fixed the issue 
Thanks

**Comment by LeoHere** [comment]
Good to know. Closing the issue.
