### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Maaarek** [UXDivers/Gorilla-Player-Support#175]
HI,

I am getting every time the same message that "Unable to connect to localhost:9014". I already turnd off the firewall but i still does not work. What can I do ?

Thanks for any help

**Comment by LeoHere** [comment]
Did you see the [Troubleshooting Connectivity Guide](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Troubleshoouting-Connectivity)?

**Comment by Maaarek** [comment]
Yes,
I can not oopen  http://localhost:9014 in the browser, I always get an unable message. It looks like that the 9014 is not running. How can  I start that ?

**Comment by LeoHere** [comment]
The server should be up and running as soon as you sign in to Gorilla Player desktop app. Did you do this, right? Try going to the system tray icon, quit Gorilla and then reopen it again.

Can you still not reach Gorilla going to http://localhost:9014 in your desktop browser?

If the problem persists, can you please send me the [logs files](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-Player-logs-location)?

**Comment by Maaarek** [comment]
The Gorilla player on my device works now, only visual studio can not connect to localhaost:9014. 
Yes of course i can send you the files. Do you want the entire folder ?

**Comment by LeoHere** [comment]
I just uploaded a [Getting Started](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Getting-Started) document. Please follow the steps described there to start previewing. 

In order to start previewing you need to deploy the player, not your own app. 

Please let me know if you have any issue.

**Comment by Maaarek** [comment]
I is working now. I am using the port 8081 and it is awesome. I got your email and read the the documentation. It is written that "Tools->Gorilla Player->FollowMe" is default but it was not. I only activated "FollowMe" and after that it was working.

**Comment by Maaarek** [comment]
Is it maybe possible to use the gorilla player for Xamarin android native ?

**Comment by LeoHere** [comment]
Good to know! 
Gorilla is just for Xamarin Forms.

Please remember to close the issue.

**Comment by Maaarek** [comment]
It not the end of the story. I used today the gorilla player for the same application i changed nothing. I could only use the gorilla player in the emulator. The GP on my physical device can not find the server. I already tried the manual setup but it did not work. I uninstalled the player on my phone and installed it again but it changed nothing.

**Comment by Maaarek** [comment]
It is working now but it is very strange because the emulator on my phone works only depending on my network connection.
