### ISSUE TITLE
Where is "UXDivers.Artina.Player" to get sample data working?

### ISSUE THREAD

**Issue by danieljaguiar** [UXDivers/Gorilla-Player-Support#181]
I am struggling to find the dll for "UXDivers.Artina.Player" in order to get the following NS working...

xmlns:common="clr-namespace:UXDivers.Artina.Player;assembly=UXDivers.Artina.Player.Common">

The bottom line is that I can't get sample data working no matter what I do... I tried installing Nuget, SDK, using SampleData.Json, using ResourceDictionary, and can't get it working and I think it is because of the dll.

**Comment by LeoHere** [comment]
@danieljaguiar sorry for the delay. The assembly name should be ```UXDivers.Gorilla.Common.dll``` not ```UXDivers.Artina.Player.Common``` (it was renamed at some point). ```UXDivers.Artina.Player.Common``` is included in ```UXDivers.GorillaPlayer.Common``` nuget packages. The SDK depends on it so if you added it you should get this package too.

Where did you get the line 
~~~
xmlns:common="clr-namespace:UXDivers.Artina.Player;assembly=UXDivers.Artina.Player.Common">
~~~

from?

I recommend to use ```SampleData.json``` as the sample data provider. What specific issue did you had with it? Can you provide a sample project so I can help you fix the issue faster?

**Comment by danieljaguiar** [comment]
@LeoHere sorry for the delay. I still finishing some urgent backlog, I should get back to Gorilla in 3 to 5 days.

**Comment by danieljaguiar** [comment]
Hi @LeoHere 

> Where did you get the line
> 
> xmlns:common="clr-namespace:UXDivers.Artina.Player;assembly=UXDivers.Artina.Player.Common">
> 
> from? 

I got it from here: https://github.com/UXDivers/Gorilla-Player-Support/wiki/Working-with-sample-data#using-jsondata-class

In the link above, it has an example where it says:

`<ContentPage
xmlns:common="clr-namespace:UXDivers.Artina.Player;assembly=UXDivers.Artina.Player.Common">
<ContentPage.Resources>`

----------------------------------------

About the SampleData.json!

I already tried it, but I can't get it working.

Here is a Sample Project: https://github.com/danieljaguiar/testgorillarepo

MainPage.xaml is:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestGorilla"
             x:Class="TestGorilla.MainPage">

  <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
    <Label Text="TEST "  HorizontalOptions="Center"/>
    <ListView ItemsSource="{Binding .}">
      <ListView.ItemTemplate>
        <DataTemplate>
          <ViewCell>
            <Label Text="{Binding Name}" VerticalOptions="Center" Grid.Column="1" />
          </ViewCell>
        </DataTemplate>
      </ListView.ItemTemplate>
    </ListView>
  </StackLayout>
</ContentPage>
```

SampleData.json has:

```
{
    "MainPage.xaml" : [
        { "Name": "John", "Age":29, "Photo":"friend_thumbnail_27.jpg" },
        { "Name": "Pam", "Age":32, "Photo":"friend_thumbnail_31.jpg" },
        { "Name": "Casy", "Age":58, "Photo":"friend_thumbnail_93.jpg" },
        { "Name": "Susan", "Age":29, "Photo":"friend_thumbnail_75.jpg" }
    ]
}
```

It doesn't work.


Thanks for the help so far.

**Comment by LeoHere** [comment]
Thanks! Fixed.

Regarding your solution, I downloaded and it seems to be working fine. When I preview ```MainPage.xaml``` i see:

![image](https://cloud.githubusercontent.com/assets/16000584/20710098/a1473b12-b617-11e6-952c-c18544623478.png)

What are you seeing when you preview ```MainPage.xaml```?

May be try restarting Gorilla desktop App. Please let me know your findings.

**Comment by danieljaguiar** [comment]
> May be try restarting Gorilla desktop App. 

It worked!!!
... and it is amazing!

**Comment by LeoHere** [comment]
Good to know! Thanks. Please remeber to close the issue if it is solved.
