### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by Pant76** [UXDivers/Gorilla-Player-Support#182]
...just installed, try to login....no way...always it says credentials invalid
<img width="356" alt="schermata 2016-11-21 alle 23 00 22" src="https://cloud.githubusercontent.com/assets/3235695/20502456/65ef02c2-b03e-11e6-9812-3634bed1922d.png">

**Comment by LeoHere** [comment]
Did you verified your email? (if not, the server might be returning this generic error for any password you enter, something we need to improve for sure!)

**Comment by Slipoch** [comment]
I have this issue as well, verified still a problem after changing password. No firewall blocking the program and running in admin mode.

**Comment by LeoHere** [comment]
@Slipoch can you write me to l r o d r i g u e z at uxdivers.com and provide me the email you are using to signin so I can check the logs? Also provide me more details about the OS where you are running Gorilla.

**Comment by LeoHere** [comment]
For future reference, the problem was that the email address of the account had not been verified.
