### ISSUE TITLE
Unable to Start  Gorilla player

### ISSUE THREAD

**Issue by ludovicLegland** [UXDivers/Gorilla-Player-Support#183]
Hello,
I can't start Gorilla player, I have this error message. I install Gorilla player as administrator.

![image](https://cloud.githubusercontent.com/assets/23519117/20515039/e4af6236-b08f-11e6-9e01-7f0a76bd685a.png)
I try to find the log at the location "Users\<YOUR_USER>\.gorilla\logs" but I don't have any folder  with .gorilla.
![image](https://cloud.githubusercontent.com/assets/23519117/20515046/efbed738-b08f-11e6-9c7f-198cd53575d7.png)
There is an other way to have logs?
Thanks in advance

Ludovic

**Comment by LeoHere** [comment]
Which version of windows are your using? 32 or 64 bits?

**Comment by ludovicLegland** [comment]
![image](https://cloud.githubusercontent.com/assets/23519117/20519822/bc077e8a-b0a4-11e6-829c-58c165c51396.png)

I use Windows 32.

**Comment by LeoHere** [comment]
Gorilla only works on 64-bit systems, that is why it is complaining. 

Sorry :(

**Comment by ludovicLegland** [comment]
Thanks for your answer. :)
Could you write somewhere the Minimum Configuration to run your program?

**Comment by LeoHere** [comment]
The following wiki document states the requirements [Installing on Desktop](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Installing-on-Desktop)
