### ISSUE TITLE
It works  but not for long

### ISSUE THREAD

**Issue by Masciuniria** [UXDivers/Gorilla-Player-Support#185]
Everything works perfectly but after 1 or 2 minutes (I guess) the server crashes. When I go to my localhost ip:9014, the browser cannot load anything. I got some doubts about my internet connection, but don't know what, i disabled the firewall.

**Comment by LeoHere** [comment]
Can you please attach your log files? (see [this](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-Player-logs-location))

**Comment by Masciuniria** [comment]
.
