### ISSUE TITLE
Shared Styles not Loading (Merged ResourceDictionarys)?

### ISSUE THREAD

**Issue by Mr-Pearce** [UXDivers/Gorilla-Player-Support#197]
Hi i have a Project with Shared Styles and Merged ResourceDictionarys  like
[Here](https://github.com/therealjohn/Xamarin-Samples/tree/master/SharedStylesTest/SharedStylesTest)
I Added the the SDK to my IOS Start Project.

Everything semms to works fine except that i get "Can't resolve resources:"
on my defined Colors and Converters inside the Themes.xaml
which are used like in the Page1.xaml

my Registration looks like "               
```
 .RegisterAssembliesFromTypes<SharedStylesLib.Themes, SharedStylesTest.App,
```

my Gorilla.json (in the SharedStylesTest Project)
```
{
	"knownAssemblies": [
		{
			"name": "SharedStylesLib"
		}		
	]
}
```

**Comment by LeoHere** [comment]
@Mr-Pearce merged dictionaries are not supported in Gorilla 0.9.1.2. Write me an email (l r o d r i g u e z at uxdivers.com) and I can provide you with the latest dev version that support them.

**Comment by LeoHere** [comment]
@Mr-Pearce is it working now? Please, close the issue if it is. Tks
