### ISSUE TITLE
Problems setting up SDK

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Gorilla-Player-Support#199]
I'm trying to set up the SDK for my project, but am running into problems when displaying pages.

My XAML page is:

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
	Title  ="About"
	xmlns ="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  xmlns:musterd="clr-namespace:Musterd;assembly=Musterd"
  x:Class="Musterd.UI.Pages.AboutPage">
    <Grid RowSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <!-- CUSTOM NAVBAR -->
        <musterd:CustomNavBar 
			Grid.Row="0" />

        <StackLayout
            Grid.Row="1"
            Grid.RowSpan="1"
			Padding    ="0,50,0,0"
			Orientation="Vertical">
            <Image
					BackgroundColor="Red"
				Source           ="{Binding ApplicationLogo}"
				HorizontalOptions="CenterAndExpand" />
            <Label
				Text             ="{Binding ApplicationName}"
				HorizontalOptions="CenterAndExpand" />
            <Label
				Text             ="{Binding ApplicationVersion}"
				HorizontalOptions="CenterAndExpand" />
            <Label
				Text             ="{Binding DatabaseName}"
				HorizontalOptions="CenterAndExpand" />
            <Button
				Margin           ="10"
				Text             ="Close"
				HorizontalOptions="CenterAndExpand"
				Command          ="{Binding CloseCommand}" />
        </StackLayout>

    </Grid>
</ContentPage>
```

And my Gorilla.json is:

```
{
  "knownAssemblies":[
        {
            "name": "Xamarin.Forms.Theme.Dark",
            "types" : null
        },
        {
            "name": "Syncfusion.ListView.XForms",
            "types" : null
        },
		{
            "name": "Syncfusion.SfNavigationDrawer.XForms",
            "types" : null
        },        
		{
            "name": "UXDivers.Artina.Shared",
            "types" : null
        },        
		{
            "name": "UXDivers.Artina.Effects",
            "types" : null
        },             
        {
            "name": "FFImageLoading.Forms.Droid",
            "types" : null
        },  
        
  ],
    "navigationPage" : {
        "all" : "true"
    }
}
```

And my assembly registration in my Main Activity is:

```
 LoadApplication (UXDivers.Gorilla.Droid.Player.CreateApplication (this,
                new UXDivers.Gorilla.Config ("Good Gorilla").RegisterAssembliesFromTypes<UI.PageModels.MainPageModel,
                                                                              FreshEssentials.ListViewItemTappedAttached,
                                                                              CircleImage,
                                                                              Syncfusion.ListView.XForms.FooterItem,
                                                                              FFImageLoading.ImageService
                                                                              > ().RegisterAssembly(typeof (UXDivers.Effects.Effects).Assembly)));
```

However, I'm getting the following error

![nexus 5 lollipop screenshot 1](https://cloud.githubusercontent.com/assets/1755678/24714371/3229cdd6-1a20-11e7-9940-f2fe2b5c48d2.png)

and the detail when tapping _Resources not found_ is:
![nexus 5 lollipop screenshot 2](https://cloud.githubusercontent.com/assets/1755678/24714430/62f3d380-1a20-11e7-951e-e4919354aa56.png)

These are defined in _MyAppTheme.xaml_, and are referred to from my _CustomNavBar_.

Also the _Unable to determine file type_ detail is:
![nexus 5 lollipop screenshot 3](https://cloud.githubusercontent.com/assets/1755678/24714535/b9ae9c46-1a20-11e7-96fb-2ba2903da076.png)

It seems that there's something pretty basic wrong with my setup!

I'm running Gorilla V 1.0.0.0

Any thoughts/suggestions?

**Comment by james-lavery** [comment]
It appears it's to do with my Grial assemblies. If I try to view a new test page with no special content, I still get the error:
![nexus 5 lollipop screenshot 4](https://cloud.githubusercontent.com/assets/1755678/24715853/e55fef4e-1a24-11e7-9997-41f4334f732c.png)

And the offending part of _App.xaml_ is:

```
 <!--  NOTIFICATION STYLES  -->
            <Style x:Key="NotificationItemTemplateShape"
                   BasedOn="{StaticResource FontIconBase}"
                   TargetType="Label">
                <Setter Property="Text" Value="{x:Static local:GrialShapesFont.Circle}" />
                <Setter Property="FontSize">
                    <Setter.Value>
                        <OnIdiom x:TypeArguments="x:Double"
                                 Phone="25"
                                 Tablet="35" />
                    </Setter.Value>
                </Setter>
                <Setter Property="Opacity" Value="1" />
            </Style>
```

**Comment by LeoHere** [comment]
@james-lavery the "Resource not found" error is because the ```MergedWith```, used in Grial ```App.xaml```, is only supported in Gorilla >=1.0.0.2. Please email JP, he can provide the appropriate Gorilla version.

**Comment by james-lavery** [comment]
@LeoHere Hi Leo - I've updated to V1.0.0.2, but am still getting the problem.
Snippet from my app.xaml is:

```
<?xml version="1.0" encoding="utf-8" ?>
<Application x:Class="Musterd.App"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
             xmlns:effects="clr-namespace:UXDivers.Effects;assembly=UXDivers.Effects"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:local="clr-namespace:Musterd;assembly=Musterd">
    <Application.Resources>
        <ResourceDictionary MergedWith="local:GrialLightTheme">
```

I still get the error screen:
![nexus 5 lollipop screenshot 5](https://cloud.githubusercontent.com/assets/1755678/24750109/9fda9f2a-1abd-11e7-951c-cf77d31c345f.png)
And the details of the Resources error:
![nexus 5 lollipop screenshot 6](https://cloud.githubusercontent.com/assets/1755678/24750129/b2a2af1c-1abd-11e7-85b1-ee2675225631.png)

I think I know how to sort the InverseBooleanValueConverter problem (I need to let Gorilla know about its assembly) - and the IsVisible error is related to this.

The _Property Label.Text was banned_ error is interesting. The details are:
![nexus 5 lollipop screenshot 8](https://cloud.githubusercontent.com/assets/1755678/24750278/2c4dc306-1abe-11e7-80f0-0637e7984e4b.png)

This looks like a Grial/Gorilla Player problem I'm afraid!

**Comment by LeoHere** [comment]
Couple of questions:
- Where are themes located?
- If you run the app it works as expected?
- Can your attach your AppDelegate or at least the portion related to Gorilla SDK setup?
- Regarding the OnIdiom error, that is something I will need to take a look at. I will let you know as soon as I do.

**Comment by james-lavery** [comment]
* Themes are in (PCL project root)/Themes, so:
    * (root)/Themes/GrialLightTheme.xaml
    * (root)/Themes/GrialDarkTheme.xaml
* App runs fine

MainActivity is here:

```
using Android.App;
using Android.Content.PM;
using Android.OS;
using FreshMvvm;
using Musterd.Core.Droid;
using Musterd.Interfaces;
using Xamarin;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using RAL;
using Android.Content;
using Android.Nfc;
using Musterd.Core.Droid.RAL;
using Acr.DeviceInfo;
using Musterd.Core.Droid.RAL.C4000;
using Android.Views;
using FFImageLoading.Forms.Droid;
using UXDivers.Artina.Shared;
using UXDivers.Artina.Shared.Droid;
.
.
.
(in OnCreate)
#if !GORILLA_PLAYER
            MusterdApplication = new App ();
            LoadApplication (MusterdApplication);

#else
            LoadApplication (UXDivers.Gorilla.Droid.Player.CreateApplication (this,
                new UXDivers.Gorilla.Config ("Good Gorilla").RegisterAssembliesFromTypes<UI.PageModels.MainPageModel,
                                                                              Converters.InverseBooleanValueConverter,
                                                                              FreshEssentials.ListViewItemTappedAttached,
                                                                              CircleImage,
                                                                              Syncfusion.ListView.XForms.FooterItem,
                                                                              FFImageLoading.ImageService
                                                                              > ().RegisterAssembly (typeof (UXDivers.Effects.Effects).Assembly)));
#endif

```

**Comment by LeoHere** [comment]
Thanks for the info.

The problem might be related to the fact that ```Musterd``` is not registered in ```Gorilla.json``` known assemblies. And the ```MergedWith```. 

Two things to try:
1) Remove ```knownAssemblies```. This property is optional in Gorilla >=1.0.0.0. If you don't specify it all the assemblies referenced by the project will be considered as known.
2) Add ```Musterd``` to the ```knownAssemblies```.

**Comment by james-lavery** [comment]
@LeoHere So I've remove the KnownAssemblies -my Gorilla.json now looks like:

```
{
    "navigationPage" : {
        "all" : "true"
    }
}
```

My MainActivity is unchanged, with the configuration being:

```
#if !GORILLA_PLAYER
            MusterdApplication = new App ();
            LoadApplication (MusterdApplication);

#else
            LoadApplication (UXDivers.Gorilla.Droid.Player.CreateApplication (this,
                new UXDivers.Gorilla.Config ("Good Gorilla").RegisterAssembliesFromTypes<UI.PageModels.MainPageModel,
                                                                              Converters.InverseBooleanValueConverter,
                                                                              FreshEssentials.ListViewItemTappedAttached,
                                                                              CircleImage,
                                                                              Syncfusion.ListView.XForms.FooterItem,
                                                                              FFImageLoading.ImageService
                                                                              > ().RegisterAssembly (typeof (UXDivers.Effects.Effects).Assembly)));
#endif
```

Unfortunately - still the same errors.

**Comment by LeoHere** [comment]
Did you restarted Gorilla desktop app after doing those changes? If not, please do. It should not be necessary but lets test that just in case there is an error processing those changes.

Also, can you double check that you desktop version of gorilla is 1.0.0.2? I mean, check that is was correctly updated once you installed it. You can see this in the about page.

**Comment by james-lavery** [comment]
@LeoHere - Aha! The desktop is still 1.0.0.0. The link from JP only had the NuGet packages for 1.0.0.2, not the desktop app.

I'll ask JP for the 1.0.0.2 of the desktop app too.

**Comment by james-lavery** [comment]
Aha! That was it! I hadn't installed the latest player app (was fooled by the exe/dmg having the name V1.0.0.0 rather than V1.0.0.2).

Thanks - up and running now.

**Comment by marcelojmacedo** [comment]
Hi guys, I am having the same problem here. Where have you got the version V1.0.0.2 of Gorilla player?
What is JPs email address?

**Comment by LeoHere** [comment]
@marcelojmacedo write me to l r o d r i g u e z at uxdivers.com. I will share it with you.

**Comment by nazgul87** [comment]
Hi @LeoHere , has the v1.0.0.15 of Gorilla player support for "OnIdiom" sentences directly on XAML?
Can you share me v1.0.0.2?

Thanks.

**Comment by LeoHere** [comment]
@nazgul87 v1.0.0.15 is the newest version. Are you having issues with the `OnIdiom`? Can you share the XAML you are trying to preview?

**Comment by nazgul87** [comment]
Oh, great. I tought that 1.0.0.2 was really 1.0.0.20.

And yeah, I'm testing with a very simple XAML and I'm having issues with OnIdiom.

This is my Code:

`<?xml version="1.0" encoding="utf-8" ?>`
      `<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"`
`			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"`
`			 x:Class="LoginModule.Views.LoginPage">`
`	<ContentPage.Content>`
`		<OnIdiom>`
`			<OnIdiom.Phone>`
`				<Label Text="Phone view"`
`					   VerticalOptions="Center"`
`					   HorizontalOptions="Center" />`
`			</OnIdiom.Phone>`
`			<OnIdiom.Tablet>`
`				<Label Text="Tablet view"`
`					   VerticalOptions="Center"`
`					   HorizontalOptions="Center" />`
`			</OnIdiom.Tablet>`
`		</OnIdiom>`
`	</ContentPage.Content>`
`</ContentPage>`

And this is the message I'm receiving:
![screenshot_20170817-171931](https://user-images.githubusercontent.com/24664303/29436315-85961c72-8370-11e7-9184-e49c44b03025.png)

am I missing something to make it work???

Thanks in advance
