### ISSUE TITLE
How to reference custom controls for presentation in Gorilla?

### ISSUE THREAD

**Issue by jonashjordie** [UXDivers/Gorilla-Player-Support#20]
This is not really a bug, just need some clarification of what's possible: 

I tried to modify the default Gorilla Player solution, to include a simple PCL library with an extended listview control, just for trying out how I could reference custom controls.

I have added the control below to a newly added Player.MyControlLibrary PCL project: (in the Gorilla Player solution), and added a reference to this PCL library in the Player.Droid project.

````c#
using System;
using System.Windows.Input;
using Xamarin.Forms;

namespace Player.MyControlLibrary
{
	public class ListViewWithTapHandler : Xamarin.Forms.ListView
	{

		public static BindableProperty ItemClickCommandProperty = BindableProperty.Create<ListViewWithTapHandler, ICommand>(x => x.ItemClickCommand, null);


		public ListViewWithTapHandler()
		{
			this.ItemTapped += this.OnItemTapped;
			var tapGestureRecognizer = new TapGestureRecognizer();
			tapGestureRecognizer.Tapped += (s, e) =>
			{

				// handle the tap
				if (this.ItemClickCommand != null)
				{
					this.ItemClickCommand.Execute(this.SelectedItem);
				}
			};

			this.GestureRecognizers.Add(tapGestureRecognizer);
		}


		public ICommand ItemClickCommand
		{
			get
			{
				return (ICommand)this.GetValue(ItemClickCommandProperty);
			}
			set { this.SetValue(ItemClickCommandProperty, value); }
		}


		private void OnItemTapped(object sender, ItemTappedEventArgs e)
		{
			if (e.Item != null && this.ItemClickCommand != null && this.ItemClickCommand.CanExecute(e))
			{
				this.ItemClickCommand.Execute(e.Item);
			}
		}
	}
}

````

In another project to be displayed in Gorilla, I have a ContentPage, to which I added the following namespace reference to the MyControlLibrary PCL I also referenced in Gorilla Player:
````xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"			
  xmlns:control="clr-namespace:Player.MyControlLibrary;assembly=Player.MyControlLibrary">			   		   

````

and the following control instance in the page content:

````xml
 <control:ListViewWithTapHandler x:Name="List" IsVisible="True" ItemsSource="{Binding ListItems}" RowHeight="130">
      <ListView.ItemTemplate>
        <DataTemplate>
          <ViewCell>          	
            
    		<view:ProcessOverviewListItem />              
            
          </ViewCell>


        </DataTemplate>
      </ListView.ItemTemplate>
  </control:ListViewWithTapHandler>
````

The above doesn't render the ListView in the page in Gorilla (it works when actually running the app). I was just guessing that this would be possible, maybe I am missing something, maybe the **ListViewWithTapHandler** class needs to be registered somehow in the Gorilla Player? I can't see the difference from including the Gorilla SDK into my own app, and letting it run as a player, since the same classes would be available through Reflection either way. (I haven't tried the SDK yet, since I wanted to separate concerns, and wanted to keep things simple)

The point is that I would make a simple shared assembly package to be included in both the standard player, as well as in my projects, for all the basic stuff I reuse across projects.

**Comment by LeoHere** [comment]
First of all, I must said that the SDK / extending Gorilla are still in its early stages. It is still immature and not very well documented.  Our plan to improve it in version 0.8.3.

There is not much difference from what you are doing to using the SDK in your App. You can put the SDK where your stuff is or you can put your stuff where the SDK is. The player is built on top of the SDK, so you are doing the latter.

From what you described I think what remains is letting know Gorilla that your control library assembly should be considered as a known assembly.

Currently, the way of doing so is to add a file named “Gorilla.json” to the PCL project that will be displayed by Gorilla. The content of the file should be:

~~~
{
  "knownAssemblies":[
	  {
		"name": "PlayerMyControlLibrary",
		"types": null
	  }
	]
}  
~~~

Ignore “types” for now, just leave it null.

Also, please make sure that the PlayerMyControlLibrary get deployed to the device, especially if you are testing in iOS.

After adding Gorilla.json, you should be able to see your list. 

**Note**: Once you add the Gorilla.json, if you attempt to preview the container project with a player that does not have PlayerMyControlLibrary it will crash. That is something we plan to fix…

**Comment by james-lavery** [comment]
This is very useful. However, how do I 'make sure the PlayerMyControlLibrary gets deployed to the device' when just in the IDE and using Gorilla?

**Comment by roubachof** [comment]
What build action is needed for the Gorilla.json file ?

**Comment by LeoHere** [comment]
The Build Action should be set to "None"

**Comment by keerthanabala** [comment]
Hai,

I am now only started working in gorilla player. Simple xaml designs are previewed. But, Next I started in working with setting a circle image on renderer using  https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK 

but on this line "LoadApplication (UXDivers.Gorilla.Droid.Player.CreateApplication(ApplicationContext,   new UXDivers.Gorilla.Config("Good Gorilla").RegisterAssemblyFromType<UXDivers.Artina.Shared.CircleImage>()));"

i am getting error in "Artina" Please, Can any one tell why this was coming ??

**Comment by LeoHere** [comment]
The sample used in the document shows how to render the ```CircleImage``` control provided in [Grial UI Kit](http://www.grialkit.com). It is just a sample to illustrate how it works. In order for that code to actually compile in your solution you need to have Grial included in your solution.

Open the XLabs Sample to se another example of this code in action.

Hope it helps.

**Comment by LeoHere** [comment]
This is a pretty old issue, for those of you reading this please take a look at [this](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) document for instructions on how to use Gorilla SDK. 

I'm closing the issue.

@keerthanabala, if you have any other problema please open a new issue.

**Comment by keerthanabala** [comment]
Thanks a lot Leo. For downloading a Grial UI kit in Website, it asking payment. Is it possible to download in open source?

**Comment by LeoHere** [comment]
No. But as I said, you can check how the SDK is used with the XLabs sample.
