### ISSUE TITLE
GorillaCriticalException on iOS device with Xamarin.Forms_2.3.4.231

### ISSUE THREAD

**Issue by iforlife** [UXDivers/Gorilla-Player-Support#203]
This happens only when deployed to iPhone - latest iOS. When deployed to simulator(also latest iOS) it works fine.
Works fine with the version from the sample - 2.2.0.45.

Crashes on LoadApplication:
var gorillaConfiguration = new UXDivers.Gorilla.Config("Gorilla on mymac.local")							.RegisterAssemblyFromType<ViewModels.DesignTimeData>();
LoadApplication(UXDivers.Gorilla.iOS.Player.CreateApplication(gorillaConfiguration));

There is also the Message from the Exception:
There was an issue instantiating Gorilla platform specific services. Is Gorilla (+ dependencies) installed in the platform specific project? (service not found JSONLoader)

![screen shot 2017-04-25 at 4 37 51 pm](https://cloud.githubusercontent.com/assets/11709259/25388128/96b1942c-29d5-11e7-957a-5771ec4add69.png)

P.S. How can I get the latest version? I saw on your blog that there is newer version with lots of improvements :(

**Comment by LeoHere** [comment]
The ```JSONLoader``` is a service exposed through the XF dependency service. Using the standard ```Dependency```. This error occurs when Gorilla is not able to resolve the service. 

You can workaround this issue by adding 
~~~
var json = typeof(UXDivers.Gorilla.Platform.JsonLoader);
~~~

in the ```AppDelegate.cs``` before the ```LoadApplication```. 

Send me an email to l r o d r i g u e z at uxdivers.com and I will send the download links for the new version.
