### ISSUE TITLE
Feedback: improve UX of gorilla player connect screen on landscape.

### ISSUE THREAD

**Issue by Bartmax** [UXDivers/Gorilla-Player-Support#205]
Right now, the top section of gorilla player takes half the space of the screen. Even having only one server the connect button and handshaking message requires scrolling the device on landscape. (at least on iPhone 6 Plus)

Making the "banner" smaller will improve this experience.

**Comment by LeoHere** [comment]
@Bartmax thanks for your feedback. The **Connect** UI has been completely redone for the next version of Gorilla. One of the goals was to remove that big header, since as you said, takes too much space. Thanks!
