### ISSUE TITLE
Issue registering Solution

### ISSUE THREAD

**Issue by cjhannon84** [UXDivers/Gorilla-Player-Support#210]
Hi,  I am currently getting this: 
![image](https://cloud.githubusercontent.com/assets/4202265/26688087/9b3bdabc-46e9-11e7-98df-127ace483442.png)

My Server is listening correctly from what i can see:

![image](https://cloud.githubusercontent.com/assets/4202265/26688157/d7a3c7bc-46e9-11e7-8c72-d37d9b24c74e.png)

**Comment by cjhannon84** [comment]
Anti virus was causing issues

**Comment by LeoHere** [comment]
Ok, thanks for letting us know. Can you elaborate on how you end up in that conclusion and how you fix it? Just in case any one experience the same issue. Tks
