### ISSUE TITLE
Problem using Grial license in own project

### ISSUE THREAD

**Issue by damiondaly** [UXDivers/Gorilla-Player-Support#211]
We have just purchased a licence for Grial and are looking for help in using that in our own project rather than the downloaded starter project.
We amended the MainActivity.cs, installed the appropriate nuget and Grial nuget packages, but we seem to have a problem with the license, the error is below:

"UXDivers.Artina.Shared.LicenseException: Internal license validation error."

For info, the starter app we created online initially had a different name from the app we want to use Grial in, we did rename the online one but still get this message.
Can you provide any helpful information?

**Comment by LeoHere** [comment]
@damiondaly closing the issue since you already found the solution. Please notice that the issue was created under the Gorilla project, not Grial. For future queries you might have, please post it under the Grial project.
