### ISSUE TITLE
can't resolve resource issue

### ISSUE THREAD

**Issue by Faizaloh** [UXDivers/Gorilla-Player-Support#214]
Hi guys I am using Grial UI Kit and i got this error when i am using gorilla player 
<img width="384" alt="screen shot 2017-06-21 at 10 31 00 am" src="https://user-images.githubusercontent.com/29616236/27411802-df24b3a6-56f8-11e7-9af7-ddc1ae3d3734.png">
<img width="381" alt="screen shot 2017-06-21 at 10 30 47 am" src="https://user-images.githubusercontent.com/29616236/27411804-e2d1697c-56f8-11e7-8282-b6d8d92d5004.png">
i try to figure out how I can fix it but there i can't
i try to contact with hello@grialkit.com for support 
and they recommended me contact with you
thx

**Comment by LeoHere** [comment]
@Faizaloh Gorilla 0.9.1.2 does not support merged dictionaries, that is why it can't find those resources. Write me to l r o d r i g u e z at uxdivers.com and I will share with you the latest version of Gorilla.

**Comment by Faizaloh** [comment]
thanks @LeoHere  check your mail please

**Comment by LeoHere** [comment]
Closing the issue. Feel free to reopen it or create a new one if you have further issues.
