### ISSUE TITLE
It's not working on newst VS2017 (15.2 (26430.14))

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [UXDivers/Gorilla-Player-Support#215]
It's not working on newst VS2017 (15.2 (26430.14))

**Comment by LeoHere** [comment]
@nguyenthanhliemfc did you installed the Gorilla Addin available in the VS Marketplace?

**Comment by nguyenthanhliemfc** [comment]
every thing working fine before I update my VS2017. After update I cannot file Gorilla in Menu of VS2017. I have try uninstall and reinstall but it still not working

**Comment by LeoHere** [comment]
Yesterday I upgraded VS to the same version you mentioned and Gorilla kept working as usual.  I have just tried to uninstall and reinstall it from the Marketplace and it works as expected. Can you send me the logs to l r o d r i g u e z at uxdivers.com?

**Comment by nguyenthanhliemfc** [comment]
Yeah. I'll try again. Thank you!

**Comment by LeoHere** [comment]
@nguyenthanhliemfc Is it working now?

**Comment by nguyenthanhliemfc** [comment]
Sorry for late reply! It's worked thank Leo. In future Gorrila Player support UWP?

**Comment by LeoHere** [comment]
@nguyenthanhliemfc thats great! That is a possibility for sure, but we still don't made any commitment to make it happen.

Closing the issue now.
