### ISSUE TITLE
Cannot show some color!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [UXDivers/Gorilla-Player-Support#216]
Cannot show some color!
Ex: SteelBlue, etc

**Comment by LeoHere** [comment]
@nguyenthanhliemfc can you provide an example of the XAML file you are trying to preview?

**Comment by nguyenthanhliemfc** [comment]
Here is my full [Project Link](https://1drv.ms/u/s!Ah-5hC3QyJDai4kioTQ3Pl8xtltwYA)

**Comment by nguyenthanhliemfc** [comment]
Here is error image [Link](https://1drv.ms/i/s!Ah-5hC3QyJDai4pdSTcS9xib2JL1Bw)

**Comment by LeoHere** [comment]
@nguyenthanhliemfc I think the issue is that Gorilla 0.9.1.2 was built against an old version of Xamarin Forms where the ```SteelBlue``` color was not defined. In order to fix it, update Xamarin Forms to the latest version in the Player solution and deploy it to your devices.

**Comment by nguyenthanhliemfc** [comment]
Thank you Leo! It's worked!
