### ISSUE TITLE
Please support auto connect!!!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [UXDivers/Gorilla-Player-Support#217]
I have one phone to run Gorilla Player and debug app. But after debug, Gorilla Player on phone disconnect. Please support auto connect, Thank you!

**Comment by LeoHere** [comment]
@nguyenthanhliemfc can you elaborate a bit more in your scenario? What are the steps you must take which let's Gorilla disconnected?

**Comment by nguyenthanhliemfc** [comment]
I only one phone to run Gorilla and Debug app. When designing my phone run Gorilla and show my UI then I star debug my phone minimize Gorilla to run my app then I stop debug Gorilla resume and don't show my UI only show name of my pc I must click Connect button. Please support auto connect.

**Comment by LeoHere** [comment]
Ok. The thing is that AutoConnect is already supported. I guess there might be a bug or Gorilla is nor properly configured. 

Is the Gorilla app in your phone the one in the store or did you deploy it yourself?

**Comment by nguyenthanhliemfc** [comment]
Yes I download from CH Play (Version 0.9.0.8) and on PC is from Visual Studio Market (Version 0.9.1.2)

**Comment by LeoHere** [comment]
Ok. For the auto-connect to work you will need to do as follows:
1. Open the Player solution installed along with Gorilla (click on "Show Player and Samples location")

![image](https://user-images.githubusercontent.com/16000584/27536921-a17030c4-5a47-11e7-956d-d883752ea0fa.png)

2. In the ```AppDelegate.cs``` and ```MainActivity.cs``` make sure the name of the Gorilla server name passed to the ```Config``` object is the same as the name of your server.

Look for a line like this:

~~~
LoadApplication (Player.CreateApplication(new Config("<NAME GOES HERE>")));
~~~

You can get the name of your server from the config.json file located in ```<User HOME>\.gorilla\config.json```

3. Deploy the Gorilla player to your device.

**Comment by nguyenthanhliemfc** [comment]
Thank you Leo! It's worked!
