### ISSUE TITLE
Question: How to determine which assemblies need to be registered with Gorilla player SDK

### ISSUE THREAD

**Issue by pcresswell** [UXDivers/Gorilla-Player-Support#220]
Just trying to get setup with gorilla player using 
Xamarin.Forms
Prism
GrialKit

Getting it working slowly. But getting a bunch of "Gorilla SDK Needed" messages telling me that basically I have some assembly missing in my setup. I'm just looking to figure out what I'm missing.

Is there anywhere in the logs that I should be looking to figure out what is still missing or why the message is appearing?

Thanks,

**Comment by LeoHere** [comment]
@pcresswell today we released Gorilla 1.0 + an GrialKit update (2.0.60). Starting with this version of Grial you can download it from the Grial Admin site with Gorilla integrated out of the box ([more info](http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html)). In addition the assemblies already pre-registered in the grial solution you will need to include those from Prism.

**Comment by pcresswell** [comment]
@LeoHere Let me download the latest. I saw the release but didn't get the sample today. Let me try that. Thanks for quick reply.

**Comment by pcresswell** [comment]
Ok, downloaded latest. I think my main problem is that my App.xaml inherits from PrismApplication which - when I browse App.xaml - the player tells me lacks a default constructor. 

@LeoHere Any chance you have another ticket on setting up a Prism Forms application? Should I add another inheritance layer to through in an empty constructor in my App.xaml?

**Comment by pcresswell** [comment]
Created a base class to inherit from PrismApplication. Added an empty constructor and updated App.xaml.

Now being told by player Root element was not recognized, nothing to display. 

Maybe didn't register some prism library correctly. Double checking.

**Comment by pcresswell** [comment]
Seems like this is closely related? (https://github.com/UXDivers/Gorilla-Player-Support/issues/12)

**Comment by LeoHere** [comment]
How are you configuring the ```Config``` object in the ```AppDelegate``` / ```MainActivity```?

At some point you should add:

~~~
   .RegisterAssemblyFromType<Prism.IActiveAware>(); // Prism
   .RegisterAssemblyFromType<Prism.PrismApplicationBase<object>>(); // Prism.Forms
   .RegisterAssemblyFromType<Prism.Unity.PrismApplication>(); // Prism.Unity
~~~

Are you explicitly declaring the ```knownAssemblies``` in your ```Gorilla.json```?. In Gorilla ```1.0.0.15``` that is not mandatory any more. Try cleaning up that property too.

**Comment by pcresswell** [comment]
Yes, those were registered. So if the root of my App.xaml file is

`<prism:PrismApplication`

Then browsing the App.xaml gives error that there is no default constructor for PrismApplication.

If I insert a new base class with a empty constructor, then the root is not recognized. 

I'm going to try and convert the Gorilla sample to use prism and compare the results to see what else I'm missing.

**Comment by pcresswell** [comment]
Hey @LeoHere  

I've created a[ repo to demonstrate the setup I have](https://github.com/pcresswell/GorillaPrism).

I've omitted my GrialLicense file on purpose so you'll need your own :)

My [App](https://github.com/pcresswell/GorillaPrism/blob/master/TUL.Trainer/App.xaml) inherits from PrismApplication currently which gets Gorilla complaining about lack of default constructor. If you change the App to inherit from [TULPrismApplication](https://github.com/pcresswell/GorillaPrism/blob/master/TUL.Trainer/TULPrismApplication.cs) then you'll get the unrecognized root error that I'm seeing.

Would really appreciate if you could point out where I'm messing up here. I'm sure it's something stupid and obvious that I should have figured out but seem to be blocked at this point.

I can take this repo down if this is a violation of any terms. Let me know. Not the intent.

**Comment by LeoHere** [comment]
@pcresswell I just downloaded the repo and tested it, but I'm not getting any error. The welcome page is previewed as expected.

Did you updated Gorilla desktop app to 1.0.0.15? (notice you need to manually uninstall the previous version before installing 1.0.0.15)

You can check the version of Gorilla in the about page.

Regarding the repo, yes please remove it. For future cases like this I can provide my email, so you can share the solution directly with me.

**Comment by pcresswell** [comment]
@LeoHere I have removed the repo. Apologies for that. 

Uninstalled Gorilla player and re-installed. Checked version 1.0.0.15 player installed.
Removed the app on iPhone device and re-installed.
Downloaded the Full Sample again from the website. Running the sample works (not using Player, just run iOS app) and displays all walkthrough screens properly on my iPhone 5. Check.

Back in VS for Mac, I checked using the player and realized that the screens were not working (believe they were working prior to 1.0 version on my system) through the player. I believe before I had started to layer on Prism that they had worked in the version I was running prior to the 1.0 update. 

Here is my LoginPage.xaml in the player for example: 

![img_3306](https://user-images.githubusercontent.com/1090039/28277702-bc9d44c0-6ae8-11e7-8a43-e10f3a43fc2c.jpg)

I had originally thought it was Prism related but now doesn't seem like it.

I notice that I'm constantly getting the warning about the SDK requirements so checking the Player logs shows this:

`{"level":"error","message":"Could not found assembly FFImageLoading with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly FFImageLoading.Platform with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly Xamarin.Forms.Platform with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared.Base with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared.Tab with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared.Repeater with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly Newtonsoft.Json with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly Lottie.Forms with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.252Z"}
{"level":"error","message":"Could not found assembly TUL.Trainer with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:43.253Z"}
{"level":"error","message":"Could not found assembly UXDivers.Effects with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.104Z"}
{"level":"error","message":"Could not found assembly FFImageLoading with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.104Z"}
{"level":"error","message":"Could not found assembly FFImageLoading.Platform with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.104Z"}
{"level":"error","message":"Could not found assembly Xamarin.Forms.Platform with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.104Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared.Base with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.104Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.104Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared.Tab with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.105Z"}
{"level":"error","message":"Could not found assembly UXDivers.Artina.Shared.Repeater with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.105Z"}
{"level":"error","message":"Could not found assembly Newtonsoft.Json with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.105Z"}
{"level":"error","message":"Could not found assembly Lottie.Forms with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.105Z"}
{"level":"error","message":"Could not found assembly TUL.Trainer with version <ANY>. It will be ignored.","timestamp":"2017-07-17T16:02:45.105Z"}`

I've attached my log files if that might help point me in the right direction but it looks like the root of the problem lies in the above and would explain why all the styling is being stripped out. 

I've confirmed that I was using the Gorilla configuration and even stripped out the #if switch to double check myself. Looking through the logs I'm seeing the same error all the time. Any thoughts? 

Much appreciate the assistance here. 
[logs.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/1153287/logs.zip)

**Comment by pcresswell** [comment]
Have tried:
1. Uninstalling VS for Mac
2. Gorilla Player
3. Downgrading nuget versions.

Can't get the vanilla sample to display the LoginPage or most other pages unfortunately.

**Comment by LeoHere** [comment]
@pcresswell the logs gave me a clue of what is wrong, which is the **player app**. You are trying to use the Player downloaded from the store to preview Grial, meanwhile you should use the player embedded in your solution. 

When you integrate the SDK to your app, you are embedding the player in your app, and making all your assemblies available for him to use them during preview time. 

In order to launch the embedded player you need to switch to the "Gorilla" configuration and deploy the app to your phone or simulator. So when you hit run in your solution (Grial based) you will see the player starting, not your app. If that is not what you see, please do a clean&rebuild&run. 

After that you know the story, just connect and start previewing your pages.

We are working on a series or videos to explain the integration and this is definitively something to show in detail, since it is not straightforward.

Please let me know if you are able to preview now.

**Comment by pcresswell** [comment]
@LeoHere you are correct. That was exactly my setup. I had completely missed the nature of the SDK requirement of being executed. I completely understood this to be design time purely. 

Once I actually run the player through the app and not the downloaded app, then things seem to be working. There's still the SDK warnings but that's likely just me missing an assembly but clearly it's now working.

Sorry about the run around but as feedback, I'd say either I completely mis-understood the documentation or the nature of the SDK vs the nature of the general player being so different threw my understanding off.

Thanks and I'm really looking forward to getting your tools and GrialKit to work:)

Thanks again.

**Comment by idubravac** [comment]
@LeoHere this should be explained better. I had the same issue. I lost 4 hours at least to figure this out. Or to be more precise I didn't - I found the answer here. I'll try to create a couple of explainer videos as well. Thx for answer.

**Comment by LeoHere** [comment]
@idubravac you will need to register all the assemblies that are referenced in the XAML files you are previewing.  Please consider also any assembly used in views or resource dictionaries being referenced.
