### ISSUE TITLE
Integration with Rider

### ISSUE THREAD

**Issue by listepo** [UXDivers/Gorilla-Player-Support#221]
Hi guys, have you plans to add [Jetbrains Rider](https://www.jetbrains.com/rider/) support?

**Comment by LeoHere** [comment]
@listepo well, we briefly considered it but we decided to wait until we get feedback from you guys. You are the first asking for it. How many are interested in Rider support?

**Comment by DamianAntonowicz** [comment]
Looking forward for Rider integration!

**Comment by HideDev** [comment]
+1

**Comment by meluskyc** [comment]
Would love to see Rider support!

**Comment by HideDev** [comment]
@LeoHere, is there any news?

**Comment by nicolaimagnussen** [comment]
is it possible to use it somewhat even though you are not fully supporting it for Rider yet?

**Comment by listepo** [comment]
Hi @LeoHere , any news?

**Comment by peresbruno** [comment]
+1

**Comment by Liberi** [comment]
+1

**Comment by HuenderBr** [comment]
+1

**Comment by marcelom56** [comment]
+1

**Comment by JorgeRomeroG** [comment]
+1

**Comment by vjlomocso** [comment]
+1
Any news?

**Comment by VFX10** [comment]
+1 Any news?

**Comment by Hocza-Jozsef-Szabolcs** [comment]
+1
