### ISSUE TITLE
No able to connect to Gorilla remote server.

### ISSUE THREAD

**Issue by kumarsathishD** [UXDivers/Gorilla-Player-Support#231]
Hi,
while trying to connect to gorilla remote server ,its throwing me the following exception .Please have a look at it .

![image](https://user-images.githubusercontent.com/30171150/28716280-f927bd42-73b9-11e7-8a50-3796cce68651.png)

**Comment by LeoHere** [comment]
When does this happen? When you try to signin? Can you disable you firewall for a moment and try again?

**Comment by kumarsathishD** [comment]
yep firewall is disabled mode only ,Please find the attached log for more information

[logs.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/1182946/logs.zip)

**Comment by kumarsathishD** [comment]
@LeoHere The issue is resolved . The Problem is that if I install the gorilla player for all users means it is not working properly and I was not able to see .gorilla folder also I think there is a bug in the installer please clarify ? If I install it for the current user means then I am able to connect to gorilla player. Now I am able to access the remote server.
any tutorials or any links on how to use gorilla player for beginners?

**Comment by LeoHere** [comment]
Great @kumarsathishD. Thanks for sharing.

Probably the [Getting Started](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Getting-Started) is what you are looking for. The [wiki](https://github.com/UXDivers/Gorilla-Player-Support/wiki) also has several other articles that might help you.
