### ISSUE TITLE
Error  'Artina' does not exist in the namespace 'UXDivers'  when integrating gorilla sdk in my application

### ISSUE THREAD

**Issue by Yorch7** [UXDivers/Gorilla-Player-Support#232]
Hi,

I'm trying to add Gorilla SDK to my solution wich has custom controls in order to use Gorilla Player, so I followed this instructions:

https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK

But I'm getting this exception:

Error CS0234 The type or namespace name 'Artina' does not exist in the namespace 'UXDivers' (are you missing an assembly reference?)	

I'm missing some nugget package? (By the way, the wiki did not specify that it had to add other nuggets packages, like UxDivers.Effects and  Xamarin.FFImageLoading.Forms)

What can I do?

**Comment by biiconsulting** [comment]
For anyone else, like me, finding this page who's a complete newb when it comes to this stuff...  

The simple answer is to the above problem is:  the usage page referenced above assumes you added Gorilla SDK to the sample Grial solution.  If that's not the case, you can remove all the ```.RegisterAssembly...``` entries in the example.

```csharp
new UXDivers.Gorilla.Config("Good Gorilla")
  // Register Grial Shared assembly
  .RegisterAssemblyFromType<UXDivers.Artina.Shared.CircleImage>() //<--Remove
  // Register UXDivers Effects assembly
  .RegisterAssembly(typeof(UXDivers.Effects.Effects).Assembly) //<--Remove
  // FFImageLoading.Transformations
  .RegisterAssemblyFromType<FFImageLoading.Transformations.BlurredTransformation>() //<--Remove
  // FFImageLoading.Forms
  .RegisterAssemblyFromType<FFImageLoading.Forms.CachedImage>() //<--Remove
));
```
Technically, you can keep the last three entries by NuGet-ing UXDivers.Effects, FFImageLoading.Transformations and FFImageLoading.Forms, but if your project doesn't require them there's not point.

Once you've removed the unnecessary ```.RegisterAssembly...``` entries, add the ones your project needs and you should be running.

**Comment by khambley** [comment]
@biiconsulting You saved my life and me pulling out all my hair! Developers except the rest of us to be mind readers! Thank you Thank you!
