### ISSUE TITLE
Your account is not active

### ISSUE THREAD

**Issue by nazgul87** [UXDivers/Gorilla-Player-Support#238]
Hi, I'm trying to login into Gorilla player but I'm getting this message:

![image](https://user-images.githubusercontent.com/24664303/29277749-32058786-80d8-11e7-9410-505b4be07f95.png)

I was using beta version some time ago, so I already have an account.

can you help me to activate my account please?

What info do you need?

Thanks in advance

**Comment by LeoHere** [comment]
@nazgul87 yes sure, please send me an email to l r o d r i g u e z at uxdivers.com from the email you used to register in Gorilla. Probably the email verification email got lost in your spam folder, and that is why Gorilla is complaining.

**Comment by marcelozanetti** [comment]
Hi, I'm trying to login into Gorilla player but I'm getting this message:

![image](https://user-images.githubusercontent.com/38536347/49402301-b7dcec80-f730-11e8-86ff-3da642e57ff8.png)
