### ISSUE TITLE
Your account is not active, please contact support

### ISSUE THREAD

**Issue by listepo** [UXDivers/Gorilla-Player-Support#240]
Hi, I have old account listepo@gmail.com and can not login. Error message 'Your account is not active, please contact support'

**Comment by LeoHere** [comment]
@listepo check again.

**Comment by listepo** [comment]
@LeoHere 
![screen shot 2017-08-15 at 23 42 01](https://user-images.githubusercontent.com/2510800/29335469-6d2c335a-8213-11e7-82c3-ecd31938fe52.png) still an error

**Comment by LeoHere** [comment]
@listepo My bad, sorry! Try again now.
