### ISSUE TITLE
Your account is not active, please contact support

### ISSUE THREAD

**Issue by sergioalejserrano** [UXDivers/Gorilla-Player-Support#241]
Hi, i have a problem with my account, "Your account is not active, please contact support"

Email: "sergioalejserrano@gmail.com"

Thanks

**Comment by LeoHere** [comment]
@sergioalejserrano are you sure that email is right? I can't find find you :(

**Comment by listepo** [comment]
@LeoHere I have this error for my new account(listepo@hotmail.com) because after Forgot your password? for my account listepo@gmail.com I did not receive the mail

**Comment by LeoHere** [comment]
@listepo I forwarded you the password reset link to listepo@gmail.com.

**Comment by listepo** [comment]
@LeoHere thanks) Gorilla Player work) thanks a lot

**Comment by sergioalejserrano** [comment]
Sorry, my mistake, I forgot that when I created my account I did the work and not personal. My deepest apologies.
