### ISSUE TITLE
Your account is not active, please contact support.

### ISSUE THREAD

**Issue by JCKodel** [UXDivers/Gorilla-Player-Support#243]
![image](https://user-images.githubusercontent.com/379339/29426851-4fa4d61a-835e-11e7-8b2c-68ca996ac1a1.png)

![image](https://user-images.githubusercontent.com/379339/29426868-5cf8aed6-835e-11e7-8770-47717ac0bcb8.png)

**Comment by LeoHere** [comment]
@JCKodel were you able to signin?

**Comment by falahati** [comment]
Same here.
I received no activation email and as the result, cant log in.

**Comment by LeoHere** [comment]
@falahati email me to l r o d r i g u e z at uxdivers.com from the email you used to register. I will manually mark you as verified.

Closing the issue now.

**Comment by Rimxak** [comment]
Hi

Can you activate this email: akortegag@inbursa.com please
Because in the company where I work, I can't send and receive extern emails from above email for intern policies of the company.

Thanks for you attention.

**Comment by LeoHere** [comment]
@Rimxak, done.

**Comment by Rimxak** [comment]
My account already works
Thanks

**Comment by AAR001** [comment]
can you active my account likedin.finder@gmail.com 
![image](https://user-images.githubusercontent.com/13041180/57289724-83070400-70d9-11e9-8fbc-efac2155d135.png)

**Comment by EfrenEspanaLopez** [comment]
hey bud could you please activate my account I try to do register with another email but I never received the email for activation email efrenespanalopez@gmail.com


![Captura](https://user-images.githubusercontent.com/8697360/61538647-74a16680-a9ff-11e9-9598-4287740694d9.PNG)
