### ISSUE TITLE
Not working on .net standard

### ISSUE THREAD

**Issue by JCKodel** [UXDivers/Gorilla-Player-Support#244]
I've created a blank project and everything works fine (I can see the XAML on my device and hot loading is working as intended).

Then, I've created a new .net standard class library and updated Xamarin Forms to version 2.4 (pre-release).

The following message is shown when I try to open a XAML from this .net standard project:

![image](https://user-images.githubusercontent.com/379339/29437394-a6b3b6ec-8386-11e7-9306-16678f39360f.png)

Logs are useless (there is only visualstudio.log and this is the tail of it:)

```
orillaVS Information: 17 : Ending Package Initialization
    ProcessId=23092
    DateTime=2017-08-17T21:25:52.9345401Z
    Timestamp=2457722050895
GorillaVS Verbose: 0 : config.json content is {"serverName":"Gorilla on SGC"}
    ProcessId=22800
    DateTime=2017-08-17T21:35:53.9595852Z
    Timestamp=2460074496986
GorillaVS Information: 1 : Starting Package Initialization
    ProcessId=22800
    DateTime=2017-08-17T21:35:53.9605882Z
    Timestamp=2460074500597
GorillaVS Information: 3 : Preferences: Host (localhost), Port (9014), UseLocalGorillaConfiguration (True), FollowMe (True), FirstTime (False)
    ProcessId=22800
    DateTime=2017-08-17T21:35:53.9741243Z
    Timestamp=2460074554252
GorillaVS Information: 17 : Ending Package Initialization
    ProcessId=22800
    DateTime=2017-08-17T21:36:00.3206557Z
    Timestamp=2460099395630
```

**Comment by cassionandi** [comment]
Same problem here.

I have lots of logs: 

**gorillaHost.log**
`{"level":"info","message":"[Server] Client info: Platform = Android; OSVersion = 5.1.1; Device Model = samsung SM-J105M; Device Name = SM-J105M; Idiom = Phone; Screen Type hdpi\r\n","timestamp":"2017-08-23T00:02:09.457Z"}
{"level":"error","message":"[Server] Could not found assembly EngineIoClientDotNet with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.467Z"}
{"level":"info","message":"[Server] Client info: Mode Player (1.0.0.15)\r\n","timestamp":"2017-08-23T00:02:09.475Z"}
{"level":"error","message":"[Server] Could not found assembly FormsViewGroup with version <ANY>. It will be ignored.\r\nerror: Could not found assembly GCM.Client with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.475Z"}
{"level":"warn","message":"[Server] Tried to add assembly  mscorlib (version <ANY>) multiple times. Only the first one will be considered.\r\nwarn: Tried to add assembly  UXDivers.Gorilla.SDK (version <ANY>) multiple times. Only the first one will be considered.\r\n","timestamp":"2017-08-23T00:02:09.475Z"}
{"level":"error","message":"[Server] Could not found assembly Microsoft.Azure.Mobile.Client with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.476Z"}
{"level":"warn","message":"[Server] Tried to add assembly  UXDivers.Gorilla.SDK (version <ANY>) multiple times. Only the first one will be considered.\r\n","timestamp":"2017-08-23T00:02:09.476Z"}
{"level":"error","message":"[Server] Could not found assembly Mono.Android with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.476Z"}
{"level":"error","message":"[Server] Could not found assembly Newtonsoft.Json with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PCLCrypto with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.477Z"}
{"level":"error","message":"[Server] Could not found assembly PInvoke.BCrypt with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PInvoke.Kernel32 with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.477Z"}
{"level":"error","message":"[Server] Could not found assembly PInvoke.NCrypt with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PInvoke.Windows.Core with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.479Z"}
{"level":"error","message":"[Server] Could not found assembly SocketIoClientDotNet with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLite-net with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLitePCLRaw.batteries_green with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.479Z"}
{"level":"error","message":"[Server] Could not found assembly SQLitePCLRaw.batteries_v2 with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLitePCLRaw.core with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.480Z"}
{"level":"error","message":"[Server] Could not found assembly SQLitePCLRaw.lib.e_sqlite3 with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLitePCLRaw.provider.e_sqlite3 with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.Core with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.IO.Compression with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.Net.Http with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.480Z"}
{"level":"error","message":"[Server] Could not found assembly System.ObjectModel with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.Xml.Linq with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.Xml with version <ANY>. It will be ignored.\r\nerror: Could not found assembly UXDivers.Gorilla.SDK.Droid with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Validation with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.480Z"}
{"level":"error","message":"[Server] Could not found assembly WebSocket4Net with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.480Z"}
{"level":"error","message":"[Server] Could not found assembly Xamarin.Android.Support.Animated.Vector.Drawable with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.CustomTabs with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.481Z"}
{"level":"error","message":"[Server] Could not found assembly Xamarin.Android.Support.Design with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.v4 with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.v7.AppCompat with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.v7.CardView with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.v7.MediaRouter with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.v7.RecyclerView with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Android.Support.Vector.Drawable with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Forms.Platform with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Forms.Platform.Android with version <ANY>. It will be ignored.\r\nerror: Could not found assembly AppNovo.Android with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.481Z"}
{"level":"error","message":"[Server] Could not found assembly EngineIoClientDotNet with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Microsoft.Azure.Mobile.Client with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Newtonsoft.Json with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PCLCrypto with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PInvoke.BCrypt with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PInvoke.Kernel32 with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.481Z"}
{"level":"error","message":"[Server] Could not found assembly PInvoke.NCrypt with version <ANY>. It will be ignored.\r\nerror: Could not found assembly PInvoke.Windows.Core with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SocketIoClientDotNet with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLite-net with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.482Z"}
{"level":"error","message":"[Server] Could not found assembly SQLitePCLRaw.batteries_green with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLitePCLRaw.batteries_v2 with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.482Z"}
{"level":"error","message":"[Server] Could not found assembly SQLitePCLRaw.core with version <ANY>. It will be ignored.\r\nerror: Could not found assembly SQLitePCLRaw.provider.sqlite3 with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.IO.Compression with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.Net.Http with version <ANY>. It will be ignored.\r\nerror: Could not found assembly System.Xml with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.482Z"}
{"level":"error","message":"[Server] Could not found assembly System.Core with version <ANY>. It will be ignored.\r\nerror: Could not found assembly UXDivers.Gorilla.SDK.iOS with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Validation with version <ANY>. It will be ignored.\r\nerror: Could not found assembly WebSocket4Net with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.482Z"}
{"level":"error","message":"[Server] Could not found assembly Xamarin.Forms.Platform with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.Forms.Platform.iOS with version <ANY>. It will be ignored.\r\nerror: Could not found assembly Xamarin.iOS with version <ANY>. It will be ignored.\r\nerror: Could not found assembly AppNovo.iOS with version <ANY>. It will be ignored.\r\n","timestamp":"2017-08-23T00:02:09.483Z"}
{"level":"error","message":"[Server] Client reported error\r\n","timestamp":"2017-08-23T00:02:09.504Z"}`

**gorillaPlayer**
(same log as above)

**visualStudio.log**
No error logs.

**Comment by nazgul87** [comment]
Same problem. Any solution???

**Comment by whitedevils** [comment]
also for me same problem, anyone has resolved it?

**Comment by peter-gabriel** [comment]
.net standard was not implemented. See [#226](https://github.com/UXDivers/Gorilla-Player-Support/issues/226)

**Comment by whitedevils** [comment]
will be there an'implementation of net standard in the future?

**Comment by ebicoglu** [comment]
is this issue known by repo owner?

**Comment by thisisthekap** [comment]
The usage .NET Standard 2.0 is critical to us. Without it we won't be able to use Gorilla Player. Any ETA on this feature would be highly appreciated.

Maybe #226 should be closed to stay focused on the issue?

**Comment by nazgul87** [comment]
Hi, do you have plans for add support for .NET Standard projects now that an stable release of Xamarin.Forms (with .NET Standard support) has been released?

**Comment by LeoHere** [comment]
@nazgul87 yes we have plans for it. @thisisthekap I can't commit to a date but we are about to start diving into this.

**Comment by LeoHere** [comment]
Hi all, we have an initial version with .Net Standard support. Anyone interested in testing it with out own project? If so please send me an email to l r o d r i g u e z at uxdivers.com. Tks.

**Comment by iemanuel** [comment]
Any news on .Net Standard support?

**Comment by whitedevils** [comment]
@LeoHere I'm available to test it with my project

**Comment by thisisthekap** [comment]
@LeoHere We would also appreciate to test the .net standard compatible version.

**Comment by gsaldana** [comment]
Hi @LeoHere, I'm very interested to test the project...I'll send you an email.

Thanks :) :+1:

**Comment by douglasbustos** [comment]
send me the solution please:  douglas.bustos101@gmail.com

**Comment by danielmeza** [comment]
Hi I want to test to, the email daniel.meza@senpai.com.co

**Comment by winstongubantes** [comment]
hi i want to test as will please sent it to my email winston.gubantes@gmail.com

**Comment by LeoHere** [comment]
Hi, Gorilla 1.2 with .NET Standard support has been released. Please check [this blog post](https://grialkit.com/2017/12/gorilla-player-1-2-net-standard-support/) for more information. Closing the issue. If you find out any issue please open a new one.

**Comment by tplooker** [comment]
Hi I am still having troubles with this, I sent my logs to your email a few days ago, did you recieve them? I couldnt find anything pertaining to why the project was failing to preview, the gorilla player host just kept restarting until it gaveup.
