### ISSUE TITLE
Gorilla SDK Needed

### ISSUE THREAD

**Issue by criistii** [UXDivers/Gorilla-Player-Support#246]
Hello,
I am using Grial UI Kit for a new Xamarin project. I have followed all instructions in setting up the environment. I am currently checking out the "Full Sample - Gorilla Ready" pregenerated solution. Each time I open an xaml file, I am getting the error: "Gorilla SDK Needed"
I checked the net, but there is absolutely no guide on how to fix this, please advice.
![21037676_10214103469890474_1025102819_o](https://user-images.githubusercontent.com/2300547/29575946-d0223878-876e-11e7-9bfe-8a083b2ec86f.jpg)

Thanks,

**Comment by LeoHere** [comment]
@criistii probably you are using the player app downloaded from the Apple store, that is why you get these errors.  

You should use the one integrated within Grial. Open `Full Sample - Gorilla Ready` solution, switch to `Gorilla` configuration, perform a clean, rebuild and deploy the app to the device or simulator. 

You will see Gorilla Player starting, not your app. Use that player to preview.

We are working on providing more clear guidance on this. Hope it helps.

**Comment by criistii** [comment]
Hi,
Thank you for the feedback. That was exactly the problem! Please consider moving the "Deploying your own compiled Gorilla Player ..." to the top of the Walkthrough page and make sure to clarify that the store app will not work properly.

**Comment by ideal-it-solutions** [comment]
good day @LeoHere  the solution did not work for me
