### ISSUE TITLE
Gorilla Embedded player XHR poll error

### ISSUE THREAD

**Issue by devp2017** [UXDivers/Gorilla-Player-Support#256]
When launching my application using the embedded gorilla player:
- if i choose a server (pc) to connect to. i get the following error : Could not establish the connection with the server (reason: xhr poll error)

If anyone can help me please

**Comment by khadeeja-alif** [comment]
I'm getting the same error :/

**Comment by LeoHere** [comment]
@khadeeja-alif after some digging the issue seems to happen once you update Gorilla SDK dependencies to the latest version (e.g. `SocketIOClientDotNet`, `EngineIoClientDotNet`). Did you update those dependencies?

We are still working on figuring out why this is happening.

**Comment by iemanuel** [comment]
i can confirm after nugget updates the same error. (reason: xhr poll error)

**Comment by pYThMik** [comment]
I have the same problem. I have indeed updated all my packages.
SocketIOClientDotNet 1.0.3
EngineIoClientDotNet 1.0.3

**Comment by rizaanlakay** [comment]
I'm getting the same issues :( Anyone find a solution yet?

**Comment by LeoHere** [comment]
@rizaanlakay if you downgrade to these versions:
- `SocketIOClientDotNet` 0.9.13 
- `EngineIoClientDotNet` 0.9.22 
- `WebSocket4Net` 0.14.1

Which are the versions used in Gorilla 1.1.0.4, it should work fine.

**Comment by rizaanlakay** [comment]
@LeoHere Awesome. Thanks for the assistance. Worked like a charm.

**Comment by leemorris** [comment]
I received the same error after upgrading several nuget packages. Downgrading the 3 that LeoHere mentioned did not resolve, I also needed to downgrade System.Net.Sockets to version 4.1.0

**Comment by pYThMik** [comment]
Gorrila SDK 1.2.0 depends on newer versions of these 3 packages. Can we update them safely now ?

**Comment by LeoHere** [comment]
@pYThMik Yes. 

This is is fixed in 1.2. Closing the issue.
