### ISSUE TITLE
Gorilla stopped after connecting to the server.

### ISSUE THREAD

**Issue by amin79** [UXDivers/Gorilla-Player-Support#258]
Hi,
I ran the Player.sln in visual studio2017 and install Gorilla successfully in my Android simulator.
 
When I run Gorilla, it connects to the server successfully with a green tick. But suddenly it will close with the message : Unfortunately , Gorilla has stopped.
![image](https://user-images.githubusercontent.com/33101184/32015783-68f36998-b9c2-11e7-9d5b-01c76f072d81.png)
![image](https://user-images.githubusercontent.com/33101184/32015868-a44d55e4-b9c2-11e7-9d1c-edaa4def5c20.png)

**Comment by jpbrocca** [comment]
Hi, could you provide more info about what are you trying to preview?

**Comment by amin79** [comment]
Thank you for your fast reply.
As I understood from the tutorials, I have at first to install Gorilla in my simulator and run it and then open any projects in Vs2017 to see the xaml forms in Simulator and I'm trying to do that.

**Comment by jpbrocca** [comment]
You are welcome!

Gorilla Player will allow you to preview "common XAML", meaning that if you are using extra stuff like custom renderers, derived pages, etc., you will probably get some issues or directly you won't be able to preview some of those things properly. For such cases you can embed Gorilla SDK on your project, then you will be able to preview more things.

Being all that said, maybe there is some peculiarity on your project which could be causing an issue (and potentially be a bug), so the more info you can provide  (like your device, if it happens on all your devices, the kind of XAML you are trying to preview, etc.) the better.

Best,
JP

**Comment by amin79** [comment]
I'm trying to use Grial UI.kit. But when Gorilla connects to the server, it has to remain open and then I open the project and go farther. But automatically and suddenly it shows the error and will be close.

**Comment by jpbrocca** [comment]
You need to use Gorilla SDK.
When you downloaded your Grial customized sample you probably noticed it provides different settings you need to choose any one with Gorilla, that way you will have all the necessary setup made.

Then, you will need to run your app and you will get Grial with preview available.

Check the docs about previewing Grial with Gorilla:
https://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-previewing-grial-with-gorilla-player

Best,
JP

**Comment by amin79** [comment]
Thank you for your great support!

**Comment by jpbrocca** [comment]
You are welcome!

Please remember to close this issue and help us to keep things tidy.

Best,
JP
