### ISSUE TITLE
Binding on page

### ISSUE THREAD

**Issue by viccotr** [UXDivers/Gorilla-Player-Support#267]
Hello, please help me.
How I can bind data for many controls on the page? 
For example page TopLvlCustomTest.xaml : 
`
<Grid HeightRequest="100" WidthRequest="200" BackgroundColor="Lime">
            
            <Label Grid.Row="0" Grid.Column="0"
                VerticalOptions="Center" HorizontalOptions="Center" VerticalTextAlignment="Center" HorizontalTextAlignment="Center"
                Text="{Binding TextLabel}" BackgroundColor="Black" FontSize="14"/>
            
            <Image Grid.Row="0" Grid.Column="1"
                Source="{Binding ImageSourceImg}"/>
            
           <BoxView Grid.Row="1" Grid.Column="0"
                BackgroundColor="Red"/>

            <ListView
                Grid.Row="1" Grid.Column="1"
                ItemsSource="{Binding .}" 
                BackgroundColor="Yellow">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Grid BackgroundColor="Aqua">
                                <Label Text="{Binding Id}" BackgroundColor="Fuchsia"/>
                                <Label Grid.Column="1" Text="{Binding HelloText}"/>
                                <Image Grid.Column="2" Source="{Binding Photo}"/>
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
            
        </Grid>
`
in SampleData.json
`
"TopLvlCustomTest.xaml": [
        {
            "Id": "Jo4hn",
            "HelloText": "sdfsdf",
            "Photo": "pic_logo_small.png"
        },
        {
            "Id": "Jo3hn",
            "HelloText": "sdfsdf",
            "Photo": "pic_logo_small.png"
        },
        {
            "Id": "Jo2hn",
            "HelloText": "sdfsdf",
            "Photo": "pic_logo_small.png"
        },
        {
            "Id": "Jo1hn",
            "HelloText": "sdfsdf",
            "Photo": "pic_logo_small.png"
        },
    ],
    {
        "TextLabel": "TestTextVal",
        "ImageSourceImg": "pic_logo_small.png"
    }
`
I see data in listView, but Label & Image - is empty. Why? 
Please help. 
Thanks

**Comment by jpbrocca** [comment]
Hi @viccotr,

The main reason is that you have not structured your JSON properly to get the binding as it is in your image.

In order to get the bindings for your image and label you need to put binding properties and values at the root level of your page JSON object:

~~~
"TopLvlCustomTest.xaml": {
   [ ... ],
   "ImageSourceImg": "pic_logo_small.png",
   "TextLabel": "TestTextVal"
}
~~~

Best,
JP

**Comment by viccotr** [comment]
Thanks a lot!
