### ISSUE TITLE
Can not connect to the server then Visual Studio 2015 crashing at opening

### ISSUE THREAD

**Issue by pbourque** [UXDivers/Gorilla-Player-Support#27]
Hello, 

I just installed the plugin for Visual Studio (0.8.2).
I got this error for a new xaml item created with visual studio.

![error1](https://cloud.githubusercontent.com/assets/14911342/12592355/0fcef0d2-c43a-11e5-8e79-62e41545a11a.png)

**Comment by pbourque** [comment]
Addition :

I try to disconnect and connect to the server in the Gorilla Player Status Windows and I've got an error message.

Thanks

![error2](https://cloud.githubusercontent.com/assets/14911342/12592365/1a555adc-c43a-11e5-8816-557b903b1e04.png)

**Comment by pbourque** [comment]
Oh :dizzy:

Now Visual Studio 2015 is crashing every time I try to open it... 
I tried to uninstall Gorilla Player, but Visual Studio keep crashing...
I've done nothing more than to installed the Gorilla Player.

I will try to repair my Visual Studio installation

I hope is only happens to me

Thanks

**Comment by jpbrocca** [comment]
Hi Philippe,

We are so sorry to hear that.
Can you send us your log files so we can try to find the reason why is this
happening on your environment?

You can find those here:
Users\<YOUR_USER>\.gorilla\logs

Did you succeed uninstalling Gorilla?
Is VS still crashing?
We will help you to fix this.

Regards and thanks,
JP

**Comment by pbourque** [comment]
Sure, there it is : 

[gorillaHost.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/105583/gorillaHost.zip)

I think I've succeeded to uninstall the Gorilla Player, but the menu still there in Xamarin Studio.
VS still crashing. 
Also, I still have access to the Log, the Lib, the Player and the Samples files in Windows Explorer under USER\.gorilla and USER\Gorilla.

I'm waiting right now for Visual Studio installer, it try to repair. 

Do you have a manual procedure for uninstalling the Gorilla Player or a better idea for fixing this? 

Thanks, I appreciate your help
Merci beaucoup

**Comment by jpbrocca** [comment]
Hi again Philippe,

You can try with this:

VSIXInstaller.exe
/u:GorillaVSAddin.UXDivers.0186dc7a-d8ea-4287-a2c2-fa7ba6133d03

Let me know how it goes.

**Comment by pbourque** [comment]
Yes!!!! 

Repair not worked, but the VSIXInstaller  command line worked.

Thank you for your support! 
You just saved me a re-installation of Visual Studio.

**Comment by jpbrocca** [comment]
Well, I wish we couldn't broke your VS first :)

Thanks for your help and patience Philippe!
We will be digging into your logs and try to find the reason why it is not
working.

Best regards,
JP




*Juan Pablo Brocca*
UXDivers Co Founder
uxdivers.com


*XAML preview for Xamarin Forms*
gorillaplayer.com


*Ready made Xamarin Forms screens in XAML*
grialkit.com

2016-01-26 19:31 GMT-03:00 Philippe Bourque <notifications@github.com>:

**Comment by philipogorman** [comment]
[gorillaHost.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/109206/gorillaHost.zip)
VS 2015 Crash at start up. 
[http://forums.xamarin.com/discussion/56072/gorilla-player-instant-xaml-preview-for-xamarin-forms/p2](url)

**Comment by jrg091** [comment]
i'm having the same issue

logs: https://drive.google.com/file/d/0ByOYozTedh9KLUhBdHNXaDNQckk/view?usp=sharing

**Comment by jpbrocca** [comment]
Hi guys, good news :)

We made a new version

**Comment by ytabuchi** [comment]
I have installed your new Gorilla Player 0.8.2.2 but VS 2015 crashed on startup. I have attached Users\<YOUR_USER>\.gorilla\logs below.

[logs.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/114956/logs.zip)

Also, I attached VS 2015 ActivityLog using devenv.exe /log into `%APPDATA%\Microsoft\VisualStudio\14.0` 

[ActivityLog.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/114962/ActivityLog.zip)

Please investigate it.

My environment is below: 
- vs 2015 update 1 japanese ui
- xamarin 4.0.0.1717

Best regards, 
yt

**Comment by jpbrocca** [comment]
Hi @ytabuchi, thank you very much for our detailed comments about this issue.
We will investigate it.

One question though: did you have the same issue with the previous version or this is the first time you tried with Visual Studio and Gorilla -0.8.2.2- ?

Thanks again!
Regards,
JP

**Comment by ytabuchi** [comment]
Hi. I have used 0.8.2.1 without any problems. after gorilla has crashed I could not launch VS. so I tried anything I could excluding uninstall vs such as devenv, deleting user local extension folder and so on.

**Comment by jpbrocca** [comment]
Hi again,
we are truly sorry about that @ytabuchi.

First things first, meanwhile we investigate please use this to uninstall Gorilal addin:
~~~
VSIXInstaller.exe
/u:GorillaVSAddin.UXDivers.0186dc7a-d8ea-4287-a2c2-fa7ba6133d03
~~~

Then you should be able to get VS working again.

Regards and again sorry,
JP

**Comment by jpbrocca** [comment]
@ytabuchi, could you attach also your `config.json` file?

You will find it also here:

`Users\<YOUR_USER>\.gorilla`

Thank you!

**Comment by ytabuchi** [comment]
Hi, please see the attached file. 
I already fix the issue with VSIXInstaller.exe ~~~ 
Thank you. 

I'm waiting for your update.
[config.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/117231/config.zip)

**Comment by jpbrocca** [comment]
Hi @ytabuchi, thank you very much!
Glad to hear you could fix the issue :)

In a few minutes I will upload a vsix which could fix your issue.

Thanks!

**Comment by jpbrocca** [comment]
Hi again @ytabuchi :)

Attached you will find the new vsix as a zip.
1) You will need to add `"logLevel":"debug"` in your `config.json` file
2) Delete all your current log files
3) Install attached vsix
4) Give it a try

In case you have any issue you can uninstall again using VSIXInstaller.exe ...

Let me know how it goes.

Best regards and thanks,
JP

[UXDivers.Artina.Player.VSAddin.vsix.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/117254/UXDivers.Artina.Player.VSAddin.vsix.zip)

**Comment by ytabuchi** [comment]
Hi @jpbrocca 
Sorry for late response. I tried your suggestion,the crash problem is still there. 

I attached my log file with "logLevel":"debug". 
If you need further information, such as VS log (I dont know where it is. so, please tell me the location...), please let me know. 

Best regards, 
yt. 
[logs.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/127305/logs.zip)

**Comment by jpbrocca** [comment]
Hi @ytabuchi 
No worries ;)
Sorry about that and thanks for the logs.
We will investigate and see if next time will be the last time we bother you with this issue.

Best regards,
JP

**Comment by jpbrocca** [comment]
Hi @ytabuchi, how have you been?

Today we released an update for Gorilla Player (0.8.3). If you could download and try it that would be great because we added more info to the logs so if this version does not fix your issue on VS I think we will have everything needed to understand your issue and fix it :)

Could you please let me know if it worked?

Thank you very much!

Best,
JP

**Comment by NelsonSantos** [comment]
Hi... 

I used the new 0.8.3 version, and get same error message, but for me, I have used a sln solution that has a unloaded project in it. 

For some reaction, the VS 2015 does not display it in the "Solution Explorer".

I read the gorillaPlayer.log file and see that as a error is on trying do load that project, like discribed in the log:

`{"level":"info","message":"Adding solution: D:\\Meus Documentos\\Google Drive\\Projetos\\EsMarca2 - Copia\\EsMarca.sln","timestamp":"2016-02-26T14:25:50.853Z"}
{"processingIssue":true,"issueType":"error","position":null,"area":"Gral","scope":"Sol","error":{"name":"Error","message":"ENOENT, no such file or directory 'D:\\Meus Documentos\\Google Drive\\Projetos\\EsMarca2 - Copia\\EsMarca\\EsMarca.WinPhone\\EsMarca.WinPhone.csproj'","stack":"Error: ENOENT, no such file or directory 'D:\\Meus Documentos\\Google Drive\\Projetos\\EsMarca2 - Copia\\EsMarca\\EsMarca.WinPhone\\EsMarca.WinPhone.csproj'\n    at Object.fs.openSync (fs.js:449:16)\n    at Object.fs.readFileSync (fs.js:286:11)\n    at Object.parser._loadProject (C:\\Program Files (x86)\\Gorilla Player\\resources\\SolutionParser.js.jx:322:34)\n    at Object.<anonymous> (C:\\Program Files (x86)\\Gorilla Player\\resources\\SolutionParser.js.jx:298:26)\n    at Object.<anonymous> (C:\\Program Files (x86)\\Gorilla Player\\resources\\SolutionParser.js.jx:430:21)\n    at Object.tryCatcher (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\util.js.jx:25:23)\n    at Promise._settlePromiseFromHandler (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:506:31)\n    at Promise._settlePromiseAt (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:580:18)\n    at Async._drainQueue (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:127:12)\n    at Async._drainQueues (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:132:10)\n    at Async.drainQueues (C:\\Program Files (x86)\\Gorilla Player\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:14:14)\n    at process._tickCallback (node.js:803:1)"},"contextInstanceId":7,"targetId":0,"sampleDataId":0,"level":"error","message":"Xaml processing error Summary:\"Fail to open project file\"; Message:\"Could not open project file \"D:\\Meus Documentos\\Google Drive\\Projetos\\EsMarca2 - Copia\\EsMarca\\EsMarca.WinPhone\\EsMarca.WinPhone.csproj\" (ENOENT, no such file or directory 'D:\\Meus Documentos\\Google Drive\\Projetos\\EsMarca2 - Copia\\EsMarca\\EsMarca.WinPhone\\EsMarca.WinPhone.csproj').\"","timestamp":"2016-02-26T14:25:50.939Z"}
{"contextInstanceId":7,"targetId":0,"sampleDataId":0,"level":"info","message":"Notifing issues found (errors: 1, warnings: 0)","timestamp":"2016-02-26T14:25:50.940Z"}
`

I removed the project for solution file (sln) and now the gorrila player work.

In case that others experience the same problem, this workarround can be used to solve it.

Regards...

Nelson

**Comment by jpbrocca** [comment]
Hi @NelsonSantos thank you very much for this!

Regards,
JP

**Comment by ytabuchi** [comment]
Hi, @jpbrocca.
Sorry for very late response. I have installed 0.8.3 
It has all gone. all cleared. Thank you!

**Comment by jpbrocca** [comment]
Hi @ytabuchi, how have you been?
Don't worry ;)
Those are really great news!

I am going to close this issue now.
Please don't hesitate to reach me if you need anything else and thanks for all your help!

Regards,
JP

**Comment by SampathTharanga** [comment]
Hi,
I install [this](https://marketplace.visualstudio.com/items?itemName=UXDivers.GorillaPlayerVisualStudioAddin#overview)  Gorilla Player for visual studio 2017. Then open the visual studio also comes [this error](https://1drv.ms/u/s!AmDk0D3FOacjkUhUELBm6z-4BWwj) . And after i will try to connect Gorilla Player then comes 
![image](https://user-images.githubusercontent.com/17849521/39048748-259ab0fe-44bc-11e8-8df0-793d40484a7d.png) this error. Please help me solve this issue.

Regards.
Sampath
