### ISSUE TITLE
Xamarin.Forms x: namespace undefined in App.xaml

### ISSUE THREAD

**Issue by BigRiceEater** [UXDivers/Gorilla-Player-Support#273]
I have installed Gorilla player on my emulator as per instructions. When I try to preview, the player will complain that the x: namespace is undefined in my App.xaml file on line such as:

`<Style x:Key="BaseEntryStyle" TargetType="{x:Type Label}">`

Some types are custom contentviews so it is not possible to remove the "x:Type" in the styles.

![image](https://user-images.githubusercontent.com/34292181/35498639-17e5ac58-050a-11e8-9a2c-bae8b0de2fa5.png)

**Comment by muffadalis** [comment]
Hi,

I am having the exact same issue. Any updates for his?

Thanks.

**Comment by Grrbrr404** [comment]
Same for me. Any solutions?

**Comment by rgclark** [comment]
You have to change the 

TargetType="{x:Type Label}"

to:

TargetType="Label"
