### ISSUE TITLE
Gorilla Player crashed after I modified applicationhots.config

### ISSUE THREAD

**Issue by FrancoisM** [UXDivers/Gorilla-Player-Support#281]
As I run a asp net backend and I want it accessible via my device, I updated the applicationhots.config file of Visual Studio to specify my ip address rather than "localhost". But then Gorilla Player crashes.

Here  is the log

> {"level":"error","message":"[Server] uncaughtException: Attribute without value\nLine: 250\nColumn: 22\nChar: i date=Wed Mar 21 2018 18:01:29 GMT+0100 (Romance Standard Time), pid=11036, uid=null, gid=null, cwd=C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0, execPath=C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\Gorilla.exe, version=v0.10.40, argv=[null, C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\Gorilla.exe, --port, 9014, --discoveryPort, 14578, --serverName, Gorilla on FOON-PC, --logLevel, info, --logLocation, C:\\Users\\franc\\.gorilla\\logs, --license, C:\\Users\\franc\\.gorilla\\license, --newConnectionContactDelay, 1000], rss=149831680, heapTotal=82008128, heapUsed=36964488, loadavg=[0, 0, 0], uptime=73770.7779084\nError: Attribute without value\nLine: 250\nColumn: 22\nChar: i\n    at error (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\sax.js.jx:667:10)\n    at strictFail (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\sax.js.jx:693:7)\n    at Object.write (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\sax.js.jx:1348:13)\n    at NuspecParser (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\NuspecParser.js.jx:84:15)\n    at Object.<anonymous> (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\SolutionParser.js.jx:659:46)\n    at DuplexWrapper.emit (events.js:98:14)\n    at endReadableNT (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\node_modules\\unzipper\\node_modules\\readable-stream\\lib\\_stream_readable.js.jx:921:12)\n    at afterTickTwo (C:\\Users\\franc\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\node_modules\\unzipper\\node_modules\\readable-stream\\node_modules\\process-nextick-args\\index.js.jx:26:10)\n    at process._tickCallback (node.js:803:1)\r\n","timestamp":"2018-03-21T17:01:29.080Z"}

**Comment by FrancoisM** [comment]
And the VSLog:

> GorillaVS Error: 76 : Exception 'Unable to connect to the remote server' ocurred while doing 'AddSolution(C:\Users\franc\Documents\Visual Studio 2017\Projects\MyProject\MyProject.sln)'. Trace    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at UXDivers.Artina.Player.Addins.Backend.<InvokeServer>d__42`1.MoveNext() in C:\UXDivers\gorilla\source\Addins\XS\XamarinAddin\Server\Backend.cs:line 361
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at UXDivers.Artina.Player.Addins.Backend.<InvokeServer>d__41`1.MoveNext() in C:\UXDivers\gorilla\source\Addins\XS\XamarinAddin\Server\Backend.cs:line 0
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at UXDivers.Artina.Player.Addins.Backend.<AddSolution>d__33.MoveNext() in C:\UXDivers\gorilla\source\Addins\XS\XamarinAddin\Server\Backend.cs:line 204.
>     ProcessId=12892
>     DateTime=2018-03-21T17:21:43.2608565Z
>     Timestamp=1556910758
>

**Comment by FrancoisM** [comment]
The crash only happens with that solution. I tried with another one and Gorilla worked fine.
I deleted my whole solution folder and re-cloned it from my remote repo thinking that would solve the problem but no, Gorilla Player crashed as soon as I open my solution.

**Comment by nexussays** [comment]
@FrancoisM  Any luck, figuring it out? I seem to be having the same issue.

**Comment by FrancoisM** [comment]
It got away by itself after a mix of restarting the pc / clean /rebuild etc.
Could not exactly tell you which of this made it go away though.

**Comment by nexussays** [comment]
@FrancoisM  Cheers, thanks
