### ISSUE TITLE
Default constructor not found for UXDivers.Gorilla.Platform.ConsoleService

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Gorilla-Player-Support#286]
Have been receiving this error in AppDelegate.cs
Default constructor not found for UXDivers.Gorilla.Platform.ConsoleService
Is there anything that needs to be done in AppDelegate too after updating Gorilla SDK ?

**Comment by khadeeja-alif** [comment]
<img width="534" alt="screen shot 2018-04-27 at 1 24 50 pm" src="https://user-images.githubusercontent.com/14857549/39352687-111bd146-4a23-11e8-855b-457318ff4518.png">
<img width="698" alt="screen shot 2018-04-27 at 1 25 10 pm" src="https://user-images.githubusercontent.com/14857549/39352689-1294eaee-4a23-11e8-85d5-ebe0ad8d3a41.png">

**Comment by khadeeja-alif** [comment]
Please help!

**Comment by jpbrocca** [comment]
Hi,
This seems to be caused by the linker.

Can you specify how it is configured?

Best
JP

**Comment by ImmenseIT** [comment]
Juan and the Grial team were awesome. They were able to resolve this in no time for us, we are back in business. Thanks a lot Great Grial Team (GGT).

Imran Founder / CEO
**Ad-Din.**
