### ISSUE TITLE
Prism : Unity container default constructor

### ISSUE THREAD

**Issue by Umar3x** [UXDivers/Gorilla-Player-Support#287]
Hello all,

First of all, thanks for making gorilla player.

However, I started a new Prism Xamarin forms application with Unity container.

When starting the app on my device, I get the following error : 

**XAML : Default constructor not found for type Prsim.Unity.PrismApplication.** 

I can't find any related doc or sample with Prism & Gorilla player. 

I also downloaded the Gorilla SDK and added it to both iOS & Android project : 

```
            LoadApplication(UXDivers.Gorilla.Droid.Player.CreateApplication(
    this,
    new UXDivers.Gorilla.Config("Good Gorilla")
      .RegisterAssemblyFromType<Prism.IActiveAware>() // Prism
        .RegisterAssemblyFromType<PrismApplicationBase>()
                        .RegisterAssemblyFromType<Prism.Unity.PrismApplication>() // Prism.Unity
    ));
        }
```

Thanks community :).

**Comment by ncunning** [comment]
not sure if this helps but one of the other post s had this
.RegisterAssemblyFromType<Prism.IActiveAware>(); // Prism
   .RegisterAssemblyFromType<Prism.PrismApplicationBase**<object>>**(); // Prism.Forms
   .RegisterAssemblyFromType<Prism.Unity.PrismApplication>(); // Prism.Unity

**Comment by Umar3x** [comment]
Hello. Thanks for your answer but I'm using Prism 7.0 and XF 3.2. If I had the <object> arguments as you say it displays an error that this constructor does not accept such arguments. Still having issue I posted 6 months ago.
