### ISSUE TITLE
Flush digital content in Gorilla Server

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Gorilla-Player-Support#297]
Hi, is there a way to flush cached content at the gorilla server?

In the iOS simulator I see the same (initial) image file whenever I try to update an image (having same name) in the resources folder of iOS. Uninstalling the App and restarting Gorilla Server seems to work but not productive for time. It takes away couple of cycles.

Any thoughts?

Thanks

**Comment by jpbrocca** [comment]
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Release-Notes-Gorilla-Player-1.0#settings-page

**Comment by IoTFier** [comment]
Hi @jpbrocca , I could clear the image cache on the Android device.

**But, on my iOS simulator clicking on the settings button makes the screen blank.** I also get the same blank screen when I tried to access the settings from the Gorilla player App that I have deployed on the iOS simulator. How do I fix this ? Your input will be appreciated.


I understand you don't want to keep issues open. But, as request, please don't close the issues until we get to exercise / apply your suggestion with successful outcome. I will close my issues as soon as the issue is addressed.
Thanks

**Comment by IoTFier** [comment]
Hi @jpbrocca, any thought on how to address this blank screen issue when clicked on setting icon in Gorilla player in iOS Simulator? Thanks

**Comment by IoTFier** [comment]
Hi @jpbrocca , I am also experiencing big delays in getting data reflected from DesignTimeData.json into .xaml views inside the Gorilla Enabled Apps. Can you please help? 
I wish this issue was kept open to get under your radar and also in front of our community.
Thanks

**Comment by IoTFier** [comment]
Hi @jpbrocca , here is another example of Gorilla server caching partial classes when I tried to create my own View Models and Models based on the existing code base. Initially I forgot to name the class in the constructor but the after correcting the gorilla cache is not getting flushed. Yes, I did delete obj and bin folders as well.

1>------ Rebuild All started: Project: ******, Configuration: Gorilla Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
1>Helpers\FontAwesomeWeb511Font.cs(7215,29,7215,35): warning CS0108: 'FontAwesomeWeb511Font.Equals' hides inherited member 'object.Equals(object)'. Use the new keyword if hiding was intended.
1>obj\Gorilla\netstandard2.0\Views\Ecommerce\Templates\ProductsCatalogItemTemplate.xaml.g.cs(16,6,16,54): error CS0579: Duplicate 'global::Xamarin.Forms.Xaml.XamlFilePathAttribute' attribute
1>obj\Gorilla\netstandard2.0\Views\Ecommerce\Templates\ProductsCatalogItemTemplate.xaml.g.cs(20,22,20,41): error CS0111: Type 'ProductsCatalogItemTemplate' already defines a member called 'InitializeComponent' with the same parameter types
1>obj\Gorilla\netstandard2.0\Views\Ecommerce\ProductsCatalogPage.xaml.g.cs(16,6,16,54): error CS0579: Duplicate 'global::Xamarin.Forms.Xaml.XamlFilePathAttribute' attribute
1>obj\Gorilla\netstandard2.0\Views\Ecommerce\ProductsCatalogPage.xaml.g.cs(20,22,20,41): error CS0111: Type 'ProductsCatalogPage' already defines a member called 'InitializeComponent' with the same parameter types
1>Done building project "******.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by jpbrocca** [comment]
Hi @IoTFier,

Sometimes you could get the blank screen. Most of the times if you switch to another XAML page and return to the original it starts previewing again.

I have never experienced big delays working with design time data. It is almost instantly.
Perhaps are you using big volumes of data?

About the cache issue you mention on your last post:
- Basically, Gorilla won't do anything with your View Models and Models.
- Now, if you update something like the font helper you have there (`Helpers\FontAwesomeWeb511Font.cs`) and that is referenced in your XAML you will need to compile again in order to get the updated code running with Gorilla SDK, otherwise, you will be using an old version.
- This error seems to be more related to something else in your solution...perhaps you have different versions of Xamarin Forms in your different projects?

Best,
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca , when tried to clear image cache, I am still getting blank page on Gorilla App running on my iOS Simulator. Is there any finding on this issue on your end? Is there any new update coming to Gorilla server very soon?

Thanks

**Comment by jpbrocca** [comment]
HI @IoTFier,

Please check https://github.com/UXDivers/Gorilla-Player-Support/issues/298 for a possible workaround.

Best,
JP
