### ISSUE TITLE
unicode character DesignTimeData.json un

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Gorilla-Player-Support#300]
Hi @jpbrocca  and Grial UI Kit team,

While validating my UI on across 3 iOS simulator devices running iOS 11.4 and 1 android version (v8.1) my VS crashed and restarted. After the solution was reloaded I found that the data in the DesignTimeData.jso got corrupt. All icon values have been replaced to "?" (? in a square box).

Is there a way to recover these values? I don't want to waste my time in merging values from another copy of DesignTimeData.json.

Thanks

**Comment by jpbrocca** [comment]
Hi @IoTFier,

hmmm...not that I know.

FWIW, I suggest you to use Visual Studio code for editing that file.

Best,
JP
