### ISSUE TITLE
Referring to Data created for templates n-levels below 

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Gorilla-Player-Support#301]
Hi @jpbrocca  and Grial Team,

While using Grial based Tabbed page, I have added couple of Tabbed Children via NavigationPage that renders few content pages. Each Content page is a referring to a listview whose datatemplates are served by various individual templates.

I have created sample data in the DesignTimeData.json for each of those templates and it works beautifully while testing each one of those templates. But, as soon as I as start combining these templates from bottom-up approach to create the top most pages, at each stage Gorilla starts complaining with error "Missing Data" and pretty much expecting to a new copy of test data for each referred templates that are combined inside each containing page.

This is really redundant, time consuming and demanding to keep track of the maintaining same set of data across multiple level. How can I avoid this ? Any thoughts on this ?

I would appreciate your help.

Thanks

**Comment by IoTFier** [comment]
Hi @jpbrocca, any thoughts on this? 
- how to refer data in a page created under / for anotherpage in DesignTimeData.json?

**Comment by IoTFier** [comment]
Hi @jpbrocca or anyone at Grial UI Team, 

Can you please help?

I am also seeing that copy the same set of data over multiple templates (contentView) & Views (contentpages) is slowing down Gorilla server a lot to render pages. 
Please help me to avoid duplicating this data and also in the meantime please let me know any configuration that I need to do for additional resources (more memory / cpu) for Gorilla server to perform faster.

Thanks

**Comment by jpbrocca** [comment]
Hi @IoTFier,

Why don't you just set Global Design Time Data?
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Working-with-design-time-data#global-design-time-data

Best,
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca,

Using Global Design Time Data was a great recommendation. I appreciate that.
I am seeing a much better improvement with it.

Thanks you.
