### ISSUE TITLE
Error resolving assemblies for modernhttpclient

### ISSUE THREAD

**Issue by Morhpeuss** [UXDivers/Gorilla-Player-Support#303]
Hello,

I got this error:

 Xaml processing error Summary:\"Error resolving assemblies for modernhttpclient\"; Message:\"Error resolving assemblies for package \"modernhttpclient\" (ENOTDIR, not a directory 'C:\\Users\\joszel\\.nuget\\packages\\modernhttpclient\\2.4.2\\lib\\ModernHttpClient-2.4.1.zip')

The directory and file exists.

**Comment by LeoHere** [comment]
@Morhpeuss write me to l r o d r i g u e z at uxdivers.com and I will share with you an installer that should fix the issue.

**Comment by LeoHere** [comment]
This issue was fixed in Gorilla Player 1.5.0.
