### ISSUE TITLE
ContentPage.ToolbarItems doesn't render (ver 0.8.2.1)

### ISSUE THREAD

**Issue by Korayem** [UXDivers/Gorilla-Player-Support#31]
I added `ContentPage.ToolbarItems` to `MyPeople.xaml` Sample app `MyCoolCompanyApp`:

```
	<ContentPage.ToolbarItems>
		<ToolbarItem Text="Primary 1" Order="Primary" />
		<ToolbarItem Text="Primary 2" Order="Primary" />
		<ToolbarItem Text="Secondary 1" Order="Secondary" />
		<ToolbarItem Text="Secondary 2" Order="Secondary" />
	</ContentPage.ToolbarItems>
```

And Gorilla Player renderd the same view without the Toolbar

**Comment by jpbrocca** [comment]
Thanks @Korayem !

**Comment by jpbrocca** [comment]
Hi @Korayem ,

this will be fixed on Gorilla Player **0.9.1.0**.

By default the toolbar is hidden in Gorilla Player, but you can make it visible simply by adding the following to your **Gorilla.json** file in your PCL to make it always visible:

~~~
"navigationPage" : {
		"all" : "true"
}
~~~

![image](https://cloud.githubusercontent.com/assets/15996999/15993394/04516f30-30bb-11e6-95aa-588ac9601835.png)

**Comment by kibiz0r** [comment]
@jpbrocca: Is there a reference for `Gorilla.json`'s `"navigationPage"` options somewhere?

**Comment by jpbrocca** [comment]
Hi @kibiz0r,
we are updating the docs and that will be online as soon as possible.

Best,
JP

**Comment by LeoHere** [comment]
@kibiz0r [here](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Previewing-within-a-Navigation-Page) is the reference doc.

**Comment by Korayem** [comment]
Awesome work @jpbrocca, can't wait to install the new version. I had some bumps on Windows #118
