### ISSUE TITLE
Any StaticResource from App.xaml not found in Xamarin.Forms app

### ISSUE THREAD

**Issue by aleksandrsmyk** [UXDivers/Gorilla-Player-Support#316]
How can I avoid this?

Logs:
SelfLogIn:Xamarin.Forms.Xaml.XamlParseException: Position 38:72. StaticResource not found for key btnLoginRed
  at Xamarin.Forms.Xaml.StaticResourceExtension.GetApplicationLevelResource (System.String key, System.Xml.IXmlLineInfo xmlLineInfo) [0x0002c] in 

Using:
Style="{StaticResource btnLoginRed}" 

Declaration in Application xaml

> <Style TargetType="Button" x:Key="btnLoginRed">
>       <Setter Property="BackgroundColor" Value="#D10A12" />
> </Style>

**Comment by aleksandrsmyk** [comment]
@LeoHere I followed this article https://blog.xamarin.com/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/ "Getting started with Gorilla". 
I added UXDivers.Gorilla.SDK.AutoConfig, Gorilla debug constant, two files and for an exception. I downloaded Gorilla today

**Comment by LeoHere** [comment]
@aleksandrsmyk I have just tried it and I can't reproduce it.

~~~
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="TestAppXaml.App">
    <Application.Resources>
        <Color x:Key="Acolor">Red</Color>
    </Application.Resources>
</Application>
~~~

~~~
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:TestAppXaml" x:Class="TestAppXaml.MainPage">
    <StackLayout>
        <Label Text="Welcome to Xamarin.Forms!" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" TextColor="{StaticResource Acolor}" />
    </StackLayout>
</ContentPage>
~~~

Can you please be more specific in how to reproduce the issue?

**Comment by aleksandrsmyk** [comment]
@LeoHere try to declare
a Style for Button and then use it like a StaticResource.
Anyway, I created a sample project today, made all configurations, and it doesn't work for me.
Gorilla is a little tricky to start working with it. I just see that I am connected to a server, but nothing happened for me more.
Here it is a project that I try to run:
[Test1.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/2575427/Test1.zip)

**Comment by LeoHere** [comment]
@aleksandrsmyk thanks for the project. Unfortunately I still can't reproduce it :( 

I tried your project but I didn't find any `Style` definition in the `App.xaml` (?). Tried adding a style to the `App.xaml` and referenced it through a `StaticResource` from the `MainPage.xaml` and works as expected...

>> Gorilla is a little tricky to start working with it. I just see that I am connected to a server, but nothing happened for me more.

Ok. Gorilla has 3 components, IDE Addin - Desktop app - Mobile App. When your device is in the connected state it means that the Mobile App is connected to the Desktop App. What remains is connecting the IDE Addin to the Desktop app, to start previewing. 

You can connect those to from VS Tools menu as shown in the screenshot bellow.

![image](https://user-images.githubusercontent.com/16000584/48403898-bd38af80-e70d-11e8-9dba-341268e6e323.png)

**Comment by aleksandrsmyk** [comment]
@LeoHere It works for me now finally. Thank you!

**Comment by LeoHere** [comment]
Awesome!
