### ISSUE TITLE
Stick gorilla to this was disabled 

### ISSUE THREAD

**Issue by sylendra7** [UXDivers/Gorilla-Player-Support#318]
Hi,

 For me Stick gorilla to this was disabled which was attached in the screenshot.

Regards
Sylendra
<img width="260" alt="screen shot 2018-11-19 at 6 42 42 pm" src="https://user-images.githubusercontent.com/15817571/48709376-4fb7e200-ec2b-11e8-8690-326f938d8aff.png">

**Comment by LeoHere** [comment]
@sylendra7 is the IDE addin connected to the server app? (see at Tools->Gorilla Player)

**Comment by sylendra7** [comment]
Hi thanks mate I resolved the issue by going to tools and connect to the
server

But the problem is images are not loading using the FfImageloading nugget

Regards
Sylendra
