### ISSUE TITLE
SVG Image using the FFImageLoading not displaying 

### ISSUE THREAD

**Issue by sylendra7** [UXDivers/Gorilla-Player-Support#319]
Hi,

SVG Image loading from the drawable folder not working with the FFImageLoading  using the Gorilla Player.

**Comment by Umar3x** [comment]
Hello,

To help you please provide the gorilla version you are using. Are you using gorilla sdk ?

**Comment by sylendra7** [comment]
I'm using Gorilla 1.5.0.0
No I'm not using Gorilla SDK

**Comment by jpbrocca** [comment]
Hi @sylendra7,

To preview SVG files through Gorilla SDK you need to provide a string with this pattern:

- resource://{**resourceName**}?assembly={**resourceAssembly.FullName**}";

...something like this:

- resource://MyApp.Sample.ResourcesFolder.MySVGFile.svg?assembly=MyApp.Sample

Finally, you need to use your XAML this way:
~~~
<ffimageloadingsvg:SvgCachedImage>
    <ffimageloadingsvg:SvgCachedImage.Source>
        <x:String>resource://MyApp.Sample.ResourcesFolder.MySVGFile.svg?assembly=MyApp.Sample</x:String> 
     </ffimageloadingsvg:SvgCachedImage.Source>
</ffimageloadingsvg:SvgCachedImage>
~~~

Regards,
JP
