### ISSUE TITLE
Error while bulding

### ISSUE THREAD

**Issue by Onslot** [UXDivers/Gorilla-Player-Support#342]
i get this error when i build Debug Any CPU Player.Droid
The non-generic type 'PrismApplicationBase' cannot be used with type arguments	Player.Droid

**Comment by jpbrocca** [comment]
Hi @Onslot,

could you provide more details/context?
Did you make sure you are using the Gorilla SDK in your app?

Thanks,
JP

**Comment by Onslot** [comment]
Hi JP,

I only get this issue on my work workstation but it works on my laptop. For me to complete my project I will just work off my laptop since it is working and worry about the issue at a later time. Thanks for your response.
