### ISSUE TITLE
Gorilla extension package not loading in VS Mac 2019

### ISSUE THREAD

**Issue by aormsby** [UXDivers/Gorilla-Player-Support#347]
I've installed the desktop app and included the Gorilla nuget packages in my files. I can deploy to my simulators and connect to my server, but nothing happens after that. I *think* it's because the VS extension package isn't loading, but I want to double check. Regardless, this does seem like a related issue. Here's a screenshot I grabbed. Can you help?

![image](https://user-images.githubusercontent.com/1312251/56075613-51a75b00-5def-11e9-97f0-cc27838fe105.png)

**Comment by LeoHere** [comment]
@aormsby we will do a new release with support for VS 2019 shortly. In the mean time you can download a compatible extension from [here](http://bit.ly/2X7Iig0). You install it using the `Install from file..." option shown in your screenshot.

**Comment by aormsby** [comment]
Thanks, that did fix the extension loading issue.

I had some initial trouble using the player on two existing projects. For some reason, the Android builds wouldn't deploy, and the iOS build wouldn't allow the player to follow me in the IDE.

However, after creating a fresh project and following the setup instructions [here](https://devblogs.microsoft.com/xamarin/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/), I have successfully connected to both Android and iOS simulators. It seems to work great here, so perhaps I need to clean out the other project packages and rebuild. I'll work with them a bit.

I'm unsure if I should close this issue or if you would prefer to. I guess I don't know the etiquette, so I'll leave it open. Thanks again. :)

**Comment by aormsby** [comment]
Yeah, for some reason the XAML follow function doesn't work. That's the only issue I've really found so far with this fix. Otherwise, seems good.

**Comment by ismaelf** [comment]
Any estimate when the plugin update for Visual Studio Mac 2019 will be out? I'm using the previous VS version just because of its compatibility with the gorilla player.

**Comment by monetelli** [comment]
Hi @LeoHere Thank you very much, I'll close the new issue, I'll look forward to the new update of Gorilla Player, I support Gorilla Player a lot, so I made a videotutorial in Spanish to use it in VS for Windows in Xamarin.Forms. https://www.youtube.com/watch?v=jzGK-J65n48

**Comment by VegardAaberge** [comment]
> @aormsby we will do a new release with support for VS 2019 shortly. In the mean time you can download a compatible extension from [here](http://bit.ly/2X7Iig0). You install it using the `Install from file..." option shown in your screenshot.

Any update on this, when are you planning to make a new release?

I can also use 1.5.1, but the follow function doesn't work which is annoying.

**Comment by jpbrocca** [comment]
Hi @aormsby,
Gorilla Player 1.5.2.0 with support for Visual Studio was released.

https://github.com/UXDivers/Gorilla-Player-Support/releases/tag/v1.5.2.0

Regards,
JP

**Comment by aormsby** [comment]
Hey, I'm sure you're aware that the nuget package update isn't available through the nuget.org portal yet, but I did manually install the latest versions without issue.

Everything is working working great! Thanks!

**Comment by LeoHere** [comment]
@aormsby the nuget for the Gorilla Player SDK v1.5.2 is available in the nuget.org. Did you have any issues with it?

**Comment by aormsby** [comment]
Ah sorry, let me be more specific. The AutoConfig package is still not updated on nuget. It shows the 1.5.0-Beta4 release still.

![Screen Shot 2019-05-29 at 14 08 08](https://user-images.githubusercontent.com/1312251/58536648-631bb980-821b-11e9-8f72-86a8ea72e32a.png)


So instead I downloaded the newer version directly from the link above, and it's working great.
