### ISSUE TITLE
Unable to install Plug-In with Xamarin Studio 6.0

### ISSUE THREAD

**Issue by psycosyd** [UXDivers/Gorilla-Player-Support#46]
I may have a unique case, but I am running on the current alpha Channel with Xamarin Studio 6.0 and it does not detect the installed plug-in, and when I try to install it via Gorilla Player I just get the message "Oh Snap! Gorilla Player Addin for Xamarin Studio installation has failed :(" 

I also appear to not be able to edit the Path directly, which could be tricky as my machine has two copies of Xamarin Studio installed (one on the alpha, one on the stable)

**Comment by jpbrocca** [comment]
Hi @psycosyd,

Could you send us your log files?

Thanks!
JP

**Comment by psycosyd** [comment]
@jpbrocca How would I grab those? Which ones do you want?

**Comment by jpbrocca** [comment]
Hi @psycosyd,

please take a look at this page:
[Gorilla Player logs location](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/wiki/Gorilla-Player-logs-location)

...then please send us all the logs on that folder.

Best regards,
JP

**Comment by psycosyd** [comment]
See attached for logs, nothing seems to stand out on this front. Just cant install the Add-In
[logs.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/147459/logs.zip)

**Comment by jpbrocca** [comment]
Thanks @psycosyd.

We will review the logs and investigate more.

**Comment by sidNee** [comment]
Same error on mac with xamarin studio. :(

"Oh Snap! Gorilla Player Addin for Xamarin Studio installation has failed :("

**Comment by jpbrocca** [comment]
Hi @sidNee,

are you also using Xamarin Studio 6.0 ?

**Comment by sidNee** [comment]
Hi @jpbrocca ,

i have installed xamarin studio 5 and xamarin studio 6.
v5: If i try to install gorilla player addin for Xamarin Studio, I can't choose XS on my programs. It is disabled.

v6: I can choose XS from my programs, but i received the error:
"Oh Snap! Gorilla Player Addin for Xamarin Studio installation has failed :(".

**Comment by jpbrocca** [comment]
OK @sidNee thanks for the details.

**Comment by psycosyd** [comment]
Yep, sounds like the exact same setup I am seeing this issue with as well.

**Comment by Jake-a-Lake** [comment]
I tried to install the add-in manually...looks like it's looking for MonoDevelop.Core/Ide v5.9.6

**Comment by jbpoulsen** [comment]
Hey guys, i know you're busting your ass off already on this project, but i need to ask if there is a timeframe or a workaround for this issue since I'm also experiencing it with Xamarin Studio 6.0?
I've been without Gorilla Player for a month now and I'm already starting losing my mind :)

**Comment by LeoHere** [comment]
Hi @jbpoulsen,
Sorry for the delay. Support for XS 6.0 will be included in our next major release in may. In the meantime, w r i t e m e t o l r o d r i g u e z a t u x d i v e r s. c o m and I can share the addin with you.

**Comment by projoneftw** [comment]
Same issue with XS 6.0 (build 5104). Btw, the message in the logs is:
 

> {"level":"error","message":"MDTool exitcode 255","timestamp":"2016-04-30T21:14:12.527Z"}

Is there a work around for the meantime? Going back to stable XS release works?

**Comment by LeoHere** [comment]
The installer I sent your should work with XS 6.0. Also it you go back to XS 5.x you can install the addin through "Install extras".

**Comment by projoneftw** [comment]
Thanks a lot! It works great now! :)

**Comment by gaganjitgrewal** [comment]
Hi,

I have recently updated to Xamarin 6.0 and having the same problem. Can someone please share the updated build?

Thanks in advance...

**Comment by robtaireeo** [comment]
@LeoHere Is this issue fixed with the latest Gorilla Player (0.9.1.2) ?

**Comment by LeoHere** [comment]
Yes, it is. However 0.9.1.2 only includes the addin installer for Mac. If you are on Windows, please download the adding attached in [this](https://github.com/UXDivers/Gorilla-Player-Support/issues/118) post and follow the instructions to install it.   I'm closing this issue now. Please open a new one if you have any issue.
