### ISSUE TITLE
Sugestion of change: Gorilla Player SDK usage

### ISSUE THREAD

**Issue by angelocarlotto** [UXDivers/Gorilla-Player-Support#58]
Hi, i just would like to suggest a little change in the wiki about the [SDK](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK). "It almost just work" for me , if there was this few changes would save me some time. Congrats by the project , it already  save me a lot of time .

**Change this:**
 Simply add this line:
 ~~~
 //LoadApplication(new App());
 LoadApplication ( Player.Droid.Player.CreateApplication(ApplicationContext, new Player.Config("Good Gorilla")));
 ~~~

**By this:**
Simply add this line in Xamarin.Droid:
  ~~~
//LoadApplication(new App());
 LoadApplication ( UXDivers.Artina.Player.Droid.Player.CreateApplication(ApplicationContext, new UXDivers.Artina.Player.Config("Good Gorilla Droid")));
~~~

And in Xamarin.iOS:
~~~
 //LoadApplication(new App());
LoadApplication ( UXDivers.Artina.Player.iOS.Player.CreateApplication( new  UXDivers.Artina.Player.Config("Good Gorilla iOS")));
 ~~~

**Comment by jpbrocca** [comment]
Hi @angelocarlotto.
Thanks for your suggestion!
We will update the SDK document with your info.

Regards,
JP

**Comment by supreettare** [comment]
My bad, I have still not find to update the doc. I will try to complete
this over the weekend.

**Comment by jpbrocca** [comment]
Hello guys, I just updated the SDK document with the suggestions made by @angelocarlotto.
I will close this issue now. If you find anything else please don't hesitate to add a new issue.

Thanks to both of you guys, you rock! :)
Best,
JP
