### ISSUE TITLE
Custom components: No method ButtonEvent_Click found on type...

### ISSUE THREAD

**Issue by angelocarlotto** [UXDivers/Gorilla-Player-Support#60]
Why i´m i getting this error: "No method ButtonEvent_Click found on type"

Here is the link of the sample project: http://www.megafileupload.com/6k74/teste421.zip

What i´m trying to do is create custom componentes like:

**Custom componente**
`public class CustomButtonTeste:Button{
		public CustomButtonTeste(){
			BackgroundColor = Color.Red;
		}
	}`

**MyPags´s code**
`public partial class MyPage : ContentPage
	{
		public MyPage ()
		{
			InitializeComponent ();
		}
		public async void ButtonEvent_Click(object s, EventArgs e)
		{
			DisplayAlert ("a", "b", "c");
		}
	}`

**MyPags´s XAML**
`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
xmlns:local="clr-namespace:teste421;assembly=teste421" 
x:Class="teste421.MyPage">
	<ContentPage.Content>
	<StackLayout>
	<local:CustomButtonTeste Text="Sample text"  Clicked="ButtonEvent_Click">
	</local:CustomButtonTeste>
	</StackLayout>
	</ContentPage.Content>
</ContentPage>`

Any suggestions?

**Comment by LeoHere** [comment]
Hi, we are currently working on enhancing the SDK to support this kind of scenarios. Unfortunately,  there is no workaround but to remove the "Clicked="ButtonEvent_Click"" from the XAML or use Button instead of CustomButtonTeste.

**Comment by LeoHere** [comment]
This issue should be fixed in 0.9.1.2. I'm closing the issue.
