### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Adam--** [UXDivers/Gorilla-Player-Support#62]
I am unable to login and get the following error (also, see attached screenshot):
mmmhhhh...not sure what happend. May be it is a connection issue. Can you reach www.uxdivers.com in your browser?

I'm able to access uxdivers.com with no problem. I've opened up ports 9014 TCP and 14578 UDP.  This issue happens on my work computer on my work's network, but not on my personal computer on my home network.

Thanks for the help!

![2016_03_31_14_04_39_new_issue_uxdivers_gorilla_player_support](https://cloud.githubusercontent.com/assets/2179171/14185892/cb164f38-f749-11e5-934f-3067dc1f826c.png)

**Comment by LeoHere** [comment]
Hi Adam,

I think the issue is that we are not using the standard port 80 for authentication and your corporate firewall might be filtering those requests. We are fixing that issue in our next release.

Sorry for the inconvenience.

**Comment by Adam--** [comment]
What port do you use now?

**Comment by LeoHere** [comment]
8081

**Comment by Adam--** [comment]
Thanks! I'm able to connect now with that port open.

**Comment by deveshigate** [comment]
I am still getting same issue (version is 0.9.1.2). Is there any solution ?

**Comment by LeoHere** [comment]
@deveshigate version 0.9.1.2 uses default port 443 (https) for authentication. I don't thing this is a firewall issue...

Did you received a verification email and verified your account?

Please, send me an email to l r o d r i g u e z at uxdivers.com and tell me which email you used when you register to Gorilla and I will check the logs.

**Comment by erer17** [comment]
Dear All, can you please help for above issue?

![image](https://user-images.githubusercontent.com/44078627/46845911-07c5c400-ce10-11e8-9a98-ecf0480a755c.png)

![image](https://user-images.githubusercontent.com/44078627/46845959-46f41500-ce10-11e8-960f-cf8bfa6773ba.png)
![image](https://user-images.githubusercontent.com/44078627/46846031-93d7eb80-ce10-11e8-97d1-ec84cb4ffb69.png)

**Comment by fariduca** [comment]
I've got the same problem. I'm using version 1.5.5.0. Any solution ?
