### ISSUE TITLE
SampleData.json does not work

### ISSUE THREAD

**Issue by punicaaa** [UXDivers/Gorilla-Player-Support#65]
I created a new simple project to play around with sample data but it doesn't work with the SampleData.json file method.
Your example with the SampleData.json file works fine. I have no idea whats wrong with my project. 

Attached you will find my example

I'm using Visual Studio 2015 Update 2

[SampleData_Example.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/201091/SampleData_Example.zip)

**Comment by LeoHere** [comment]
Hi! Just change the build action of SampleData.json from Content to None. That should solve the issue.

We will work in improving this so it is easier to find out this kind of errors.Thanks for your feedback!

**Comment by punicaaa** [comment]
Now it is working. Thanks.

**Comment by LeoHere** [comment]
Great!
