### ISSUE TITLE
Reset Password Not Available

### ISSUE THREAD

**Issue by EdHubbell** [UXDivers/Gorilla-Player-Support#66]
Does not seem to be an option to reset my password. Or recover it. I'd love it if someone could reset it for me.

'Keep Me Logged In' was great until it timed out. I can't seem to find a web interface that allows for password reset or recovery. Please help. Trying to use this today.

**Comment by jpbrocca** [comment]
Hi could you send me an email to:

jpbrocca@uxdivers.com

...with the email account you used to register to Gorilla?

I will reset the password and send it to you ASAP.

Regards,
JP
