### ISSUE TITLE
Dates in sampledata.json

### ISSUE THREAD

**Issue by wastaz** [UXDivers/Gorilla-Player-Support#67]
How are you supposed to put dates in sampledata.json? There's no real standard for how to do dates and time in json, and none of the unoffical ways of doing it seems to work for me. :/ 
Having datetime objects as part of a viewmodel is not that far-fetched for many applications, so some documentation on how to write that type of sample data would be really nice to have.

**Comment by LeoHere** [comment]
Hi! 
This is an example:
~~~
"Label\\LabelWithStringFormat.xaml": {
  "Begin": 2016-04-28T00:00:00.000Z,
  "End": 2016-04-26T18:25:43.511Z
},
~~~

Thanks for your feedback.
