### ISSUE TITLE
Gorilla server is not started

### ISSUE THREAD

**Issue by ZuberMax** [UXDivers/Gorilla-Player-Support#68]
After my device cannot connect to server i run file located at `C:\Program Files (x86)\Gorilla Player\resources>Gorilla.exe` and then i receive next error
![2016-04-08_1-31-48](https://cloud.githubusercontent.com/assets/15868365/14368948/ba597874-fd29-11e5-8958-241879fdbeb5.png)

also as i see from logs server cannot start after i run it.
Firewall disabled, Port forwarding (9014) on my router is enabled.
logs: https://goo.gl/hJdNFd

**Comment by LeoHere** [comment]
Hi. Gorilla Player should be used through the "Gorilla Player.exe" located in "C:\Program Files (x86)\Gorilla Player\". 
Did you try it? What error did you get if any?

**Comment by ZuberMax** [comment]
Hi. Thanks for reply. Yes i try to run Gorilla Player.exe from another folder, and it's start without any error. Then it's prompt to enter my credentails, i close that window because i don't have a password(may be that's a problem ?). Next i see message "Time to see some XAML" and Gorilla icon in tray.

**Comment by LeoHere** [comment]
Yes, that seems to be the problem. Please, go to www.gorillaplayer.com and register to the beta program.

**Comment by ZuberMax** [comment]
May be i am doing something wrong, but there is a field on www.gorillaplayer.com  where i can enter my email and press button "Apply Now!", so i have already try this yesterday, but i don't receive any confirmation email, etc .

**Comment by jpbrocca** [comment]
Hi @ZuberMax.
It takes a few days until you get final access.

**Comment by ZuberMax** [comment]
Hi, @jpbrocca  
I see, thank you guys for replying me.

**Comment by jpbrocca** [comment]
Sure, anytime.

**Comment by ZuberMax** [comment]
Yes, the problem was in authentication, after i loged in everything is ok.Thanks.
