### ISSUE TITLE
Found conflicts between different versions of the same dependent assembly

### ISSUE THREAD

**Issue by SimonKaeseler** [UXDivers/Gorilla-Player-Support#69]
Hi there..

I got two machines running the Gorilla player - one that runs without any problems and one that just cant deploy to Xamarin Android Player. 

The full error is:

Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="WebSocket4Net" culture="neutral" publicKeyToken="eb4e154b696bf72a" /><bindingRedirect oldVersion="0.0.0.0-0.14.1.0" newVersion="0.14.1.0" /></dependentAssembly></assemblyBinding>	

If I let VS2015 (community) add this to an app.config file, nothing changes.
In the build output, it seems that the version of WebSockets4Net might be the issue(?) It seems to be needing 0.12.0.0.

EDIT: I've just updated VS2015 Nuget Packet manager, which might be the issue.

Hopefully there is an answer to this.

Ty

**Comment by LeoHere** [comment]
Hi @SimonKaeseler! Gorilla depends on WebSockets4Net 0.14.1. Are you using a different version in your project?

**Comment by SimonKaeseler** [comment]
Im just using the solution that came with the player, and i havent changed any default reference or package. It seems that sometimes when i deploy to xamarin player or a device, it fails and gives me the error. To clarify, this is a deployment error, the projects are building just fine.


However, now it seems to be running okay so im no longer sure this is a gorilla player issue :/

**Comment by Mohye77** [comment]
Hi @SimonKaeseler , Make sure to update your nuget packages from the package manager.
 I just had this problem solved this way.

**Comment by idenardi** [comment]
I have the same problem here.
The "Compile using Android Version" option (in the properties under android project) was empty.
After set this property to "Use Latest Plataform" everything runs fine.
