### ISSUE TITLE
Xamarin.Forms 2.1(My App) vs 2.0(Gorilla)

### ISSUE THREAD

**Issue by angelocarlotto** [UXDivers/Gorilla-Player-Support#70]
Guys, i installed the Gorilla SDK just like is discribed in here: https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK

Also i installed the Gorilla Apps in the iPhone VM.

If my app has the newer Xamarin.Forms version, do i have to update Gorilla´s player xamarin.forms as well? Or do i have to update any component of Gorilla PLayer?

I ask because i´m facing this exception:

![image](https://cloud.githubusercontent.com/assets/388386/14575493/205eeef4-0330-11e6-91be-c8c72557dc1b.png)

**Comment by LeoHere** [comment]
Hi @angelocarlotto, Gorilla 0.8.3.0 was compatible with XF 2.0. You will need to wait until our next release (May) to be able to use the SDK within XF 2.1. The new release will use nuget to manage dependencies so we can minimise this kind of annoyance.

**Comment by angelocarlotto** [comment]
Ok, thanks for the attention, @LeoHere.

**Comment by lhughey** [comment]
leo, I see that version of .90 (which addresses forms 2.1) was released on the app store today.  When will the code for the player be released?  I would like to install it on my simulator.

**Comment by LeoHere** [comment]
Hi guys, just closing this old issue. If you haven't yet please try 0.9.1.2 which is compatible with XF >= 2.1 and with the apps in the store.
