### ISSUE TITLE
Unable to compile Player.Droid (and one problem in Player.IOS)

### ISSUE THREAD

**Issue by Cypox71** [UXDivers/Gorilla-Player-Support#71]
Hi, 
I installed 0.8.3 but I have a problem trying to compile in Android(or update packages):

> Looking for updates for 'Xamarin.Android.Support.v7.MediaRouter'...
> Updating 'Xamarin.Android.Support.v7.MediaRouter' from version '23.0.1.3' to '23.3.0' in project 'Player.Droid'.
> Updating 'Xamarin.Android.Support.v7.MediaRouter 23.0.1.3' to 'Xamarin.Android.Support.v7.MediaRouter 23.3.0' failed. Unable to find a version of 'Xamarin.Forms' that is compatible with 'Xamarin.Android.Support.v7.MediaRouter 23.3.0'.
> 

In IOS, AppDelegate.cs,  I commented this row to run:
#if ENABLE_TEST_CLOUD
	//Xamarin.Calabash.Start();
#endif 

I'm a newbie in Xamarin, so... I'm doing mistakes, for sure  :)

**Comment by LeoHere** [comment]
Hi. Those packages errors you get are expected (see [this](https://forums.xamarin.com/discussion/57283/unable-to-find-a-version-of-xf-compatible-with) for more info). 

Did iOS package restoration succeeded? 

In 0.8.3, be sure not to upgrade to XF 2.1. That might bring you problems, specially in Android. Try to stay in 2.0. For our next release we are moving to nuget so we can easily deal with this XF dependency issues.

**Comment by LeoHere** [comment]
This issue is old and should not happen in 0.9.1.2. I'm closing it. Please open a new one if you are experiencing the issue.
