### ISSUE TITLE
Where to sign up?

### ISSUE THREAD

**Issue by mribbons** [UXDivers/Gorilla-Player-Support#79]
Applied for the beta program, got an invite.

Now where do I get credentials?

Have never used the Gorilla SDK before - Hoping I don't need a paid account just to try out the beta.

**Comment by LeoHere** [comment]
Hi Mike,

Once you open Gorilla Player on your desktop machine it will ask for those credentials. If you didn't install Gorilla yet please download and install it from [here](https://github.com/UXDivers/Gorilla-Player-Support/releases/tag/v0.8.3).

[This](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) tutorial will help you with the setup of the SDK.

**Comment by mribbons** [comment]
Hi Leonardo,
How do I generate those credentials?

On Tue, May 3, 2016 at 9:03 PM, Leonardo Rodríguez <notifications@github.com

**Comment by LeoHere** [comment]
You should have received an email with them, did you receive it? (we sent it 30 minutes ago)
