### ISSUE TITLE
Supporting UTF-8

### ISSUE THREAD

**Issue by reader-man** [UXDivers/Gorilla-Player-Support#82]
Hi,
 I am using ur GORILLA PLAYER to show some buttons, in non-Latin languages, like Hebrew and Arabic, but it could not render them.

can you please look into it.

**Comment by LeoHere** [comment]
Hi, thanks for your feedback. I can't reproduce this issue. Can you provide a sample solution to reproduce it?

**Comment by reader-man** [comment]
I was using this:
                <Label Text="تجربة"  />
And it was not rendering correctly.
But strangely, it looks like its working correctly now.

Thanks.

**Comment by jpbrocca** [comment]
hi @reader-man,

can we close this issue or are you still having issues?

thanks
JP

**Comment by reader-man** [comment]
Sorry too many eMails these days.

Yes, close it please, its working 100%.

**Comment by reader-man** [comment]
Thanks a lot.

**Comment by jpbrocca** [comment]
No worries, it happens all the time ;)

Have a great day!
JP
