### ISSUE TITLE
Gorilla Player can't install add-in for version 6.1 of XS

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Gorilla-Player-Support#85]
Hi all,
While the Xamarin.Forms XAML preview is all very well, Gorilla Player still does a better job!

I've upgraded to the latest beta of XS, and Gorilla Player can't install the add-in. When I try to install from the 'install extras' menu item, I get the error:

"Oh snap! Gorilla Player Addin for Xamarin Studio failed :("

Is there a log I can check to find out more information?

Version information is:
=== Xamarin Studio Enterprise ===

Version 6.1 (build 817)
Installation UUID: 462e6ba8-9cb7-4b87-acc8-9dfb0ab2c6f7
Runtime:
	Mono 4.4.0 (mono-4.4.0-branch/fcf7a6d) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 404000148

=== NuGet ===

Version: 3.3.0.0

=== Xamarin.Profiler ===

Version: 0.30.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 7.2 (9548)
Build 7C68

=== Xamarin.iOS ===

Version: 9.9.0.719 (Xamarin Enterprise)
Hash: 3afb4af
Branch: master
Build date: 2016-04-24 15:13:41-0400

=== Xamarin.Android ===

Version: 6.1.99.224 (Xamarin Enterprise)
Android SDK: /Users/jameslavery/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)

SDK Tools Version: 24.4.1
SDK Platform Tools Version: 23.1
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Version: 0.6.5
Location: /Applications/Xamarin Android Player.app

=== Xamarin.Mac ===

Version: 2.9.0.719 (Xamarin Enterprise)

=== Build Information ===

Release ID: 601000817
Git revision: 2335763551f9db8296b08542035977b899b7f3b7
Build date: 2016-04-25 10:45:36-04
Xamarin addins: 7f8c9ab2a981143a87fbd5adbde3f5890a838fde
Build lane: monodevelop-lion-cycle8-preview

=== Operating System ===

Mac OS X 10.11.0
Darwin pi-140.msec.local 15.0.0 Darwin Kernel Version 15.0.0
    Wed Aug 26 16:57:32 PDT 2015
    root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by LeoHere** [comment]
Hi James,
I just email you with the link to a XS addin 6+ compatible. This addin will be included in our next release, in the meantime those who are interested w r i t e m e t o l r o d r i g u e z a t u x d i v e r s. c o m and I can share the addin with you.

**Comment by gaganjitgrewal** [comment]
Hi Leo,

Can you please share the link to XS addin 6+ compatible with me. I am facing the same problem.

Thanks in advance.

**Comment by LeoHere** [comment]
Yes, sure. Just send me an email to the address mentioned in my previous comment.

**Comment by gaganjitgrewal** [comment]
Hi Leo,

Thanks a ton for the reply.

I cannot find any email address in your previous comment, so if you could send me your email address I will send you an email on that else you can send me the link on gaganjit.grewal@gmail.com.

Looking forward to hearing from you.

**Comment by GustavoTancredo** [comment]
Hi Leo

I'm need the file too.. please send to me my mail is gustavotancredo@gmail.com

tnks

**Comment by danielvtan** [comment]
Need the 6.1 compatible add in too. please email me danielvtan @ gmail.com

Thanks

**Comment by viscardo** [comment]
My problem is similar on my Mac

I have installed Xamarin studio 6.0.1 (build 8) and then I have installed the Gorilla Player 0.9.12 but unfortunately it seems that it is not working on xamarin.

On Xamarin Studio,  I go to Tools and there is no Gorilla option.
I tried to reinstall xamarin, reinstall Gorilla player, install extras on gorilla player and still not show the gorilla option on tools menu in Xamarin Studio.

Could someone help me ?

Thks

**Comment by LeoHere** [comment]
Please download the compatible addin from here https://goo.gl/rjYktl

**Comment by viscardo** [comment]
LeoHere,

I am not a great mac user, could you please help me how to unpack this file and where i have to copy these files to ?

Thank you once more :)

**Comment by viscardo** [comment]
It worked :+1:  Thank you

**Comment by LeoHere** [comment]
That's good. I'm closing the issue now. Feel free to open it again if you need to.

**Comment by manojsethi** [comment]
@LeoHere Can you please give the link to install addin on WindowsPC

**Comment by manojsethi** [comment]
@viscardo Can you please help me in unpacking the plugin

**Comment by 130990** [comment]
Hi @LeoHere  I have the same problem I´ve XS 6.0.2 and I´m trying to install the new gorilla player and just gave me an error, I'm working with XS in PC

**Comment by 130990** [comment]
My email is victor.rojas98@gmail.com

**Comment by LeoHere** [comment]
Victor, please install the addin attached in [this](https://github.com/UXDivers/Gorilla-Player-Support/issues/118) post. Let me know the result.
