### ISSUE TITLE
Can i use Gorrilla Player with Windows 10 Mobile?

### ISSUE THREAD

**Issue by alejoasotelo** [UXDivers/Gorilla-Player-Support#93]
Hi,

i see examples with iOS and Android but nothing with Windows 10 mobile, so my question is: can Gorrilla Player support Windows 10 mobile?

And if the answer is yes, how?

Thanks you very much!
best!

**Comment by jpbrocca** [comment]
Hi Alejo,

Gorilla player is only available at the moment for iOS and Android only.

Regards,
JP
