### ISSUE TITLE
Could not connect to the server (is it down?)

### ISSUE THREAD

**Issue by gc1508** [UXDivers/Gorilla-Player-Support#98]
The libraries on my project have been updated by NuGet to version 0.9.0.
I have also updated the libraries in player, and deployed it to a real device. 

However, now I get the message "could not connect to server". 

Any idea?

Thanks.

**Comment by LeoHere** [comment]
Yesterday we released the first version of Gorilla compatible with those packages. Please install it and test it again. You should use packages 0.9.1.2+. I will close the issue for now. Please feel free to reopen it at any time.
